- hemi/electrumx/electrumx.go
**Summary**
Fix a race condition in the electrumx client
Previously, the request ID stored in the client was incremented while the lock was held, however it was then read without the lock being held.
**Changes**
- Fix race condition in `electrumx` package
> electrumx: fix race condition in client

- go.mod
- go.sum
**Summary**
Updated version of uint256 library changes serialization. Revert to old version for now, upstream optimism contains fix and will adopt it when inheriting updates.
**Changes**
Revert uint256 library back to v1.2.3
> Revert uint256 library dependency to v1.2.3

- .github/workflows/go.yml
**Summary**
Remove use of `continue-on-error` flag in Go workflow due to it causing the workflow to suceed even if a step failed.
**Changes**
- Replace `continue-on-error` with `if: (success() || failure()) && steps.deps.outcome == 'success'` to mimic behaviour without causing the job to succeed with steps failing.
> ci: fix go workflow succeeding even if a step fails

- e2e/network_test.go
**Summary**
prior, upon investigating full network e2e tests, I was seeing the following:
* in e2e tests, we were often hitting the following error: `bfg: bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth N`
**Changes**
* generate 5000 blocks to start full network e2e test + add retry to tests in case we still try a premature spend of coinbase
* more clear ordering of checks
fixes #2
> make less likely to spend coinbase

- api/protocol/protocol.go
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
- service/bss/bss.go
**Summary**
This is a bit awkward and probably does not belong here. However, this code is copy and pasted everywhere and pretty brittle. So to prevent reinventing the wheel and bad copy paste it is allowed here.
**Changes**
Catch up remaining daemons to use this new api.
> Move internal error into protocol package

- Makefile
- e2e/mocktimism/mocktimism.go
- e2e/network_test.go
**Summary**
Add `-local` flag to `goimports` command in `make lint`, which will cause all local imports to be grouped together.
**Changes**
- Add `-local github.com/hemilabs/heminetwork` to the `goimports` command in `make lint`.
> make: add -local flag to goimports

- README.md
- e2e/docker-compose.yml
- e2e/mocktimism/mocktimism.go
**Summary**
As of now, we generate L2 Keystones and BTC Blocks at a high rate in the local network, and we don't make it easily configurable to change. This PR gives us that ease.
**Changes**
when running your local network via docker-compose, you can set the following env variables to configure the rates at which BTC Blocks and L2 Keystones are generated, respectively.
* HEMI_LOCAL_BTC_RATE_SECONDS
* HEMI_LOCAL_L2K_RATE_SECONDS
fixes #17
> allowing BTC Block and L2 Keystone generation rates to be configurable in local network

- e2e/network_test.go
**Summary**
Upon testing with @joshuasing , I realized that we generate 5000 btc blocks in our test, but we tell bfg to start at block 100.  This causes bfg to take too long to catch up.
Also, don't panic in go routines if the context is done, this can cause tests to fail when they shouldn't
**Changes** 
* start bfg btc height high so we don't take too long to process
* don't panic in go routines if context is done
> Network test start height + no panic

- docker/bfgd/Dockerfile
- docker/bssd/Dockerfile
- docker/popmd/Dockerfile
**Summary**
Update `golang` image to `1.22.1-alpine`.
Release notes: https://go.dev/doc/devel/release#go1.22.1
More information: https://github.com/golang/go/issues?q=milestone%3AGo1.22.1+label%3ACherryPickApproved
This release contains security fixes.
**Changes**
- Update `golang` image to `golang:1.22.1-alpine@sha256:fc5e5848529786cf1136563452b33d713d5c60b2c787f6b2a077fa6eeefd9114`
> docker: update golang image to v1.22.1

- .github/workflows/go.yml
**Summary**
Fix previous "Go" CI runs not being cancelled when a newer commit is pushed to a pull request.
**Changes**
- Use `github.event_name` instead of `github.event.action` in `cancel-in-progress`
> ci: fix concurrency cancel-in-progress for pull requests

- api/auth/secp256k1.go
- api/protocol/protocol.go
- bitcoin/bitcoin.go
- cmd/bfgd/bfgd.go
- cmd/bssd/bssd.go
- cmd/hemictl/hemictl.go
- cmd/keygen/keygen.go
- cmd/popmd/popmd.go
- config/config.go
- database/bfgd/postgres/postgres.go
- database/database.go
- database/postgres/postgres.go
- hemi/electrumx/electrumx.go
- hemi/pop/pop.go
- service/bfg/bfg.go
- service/bfg/bfg_test.go
- service/deucalion/deucalion.go
- service/popm/popm.go
- web/popminer/popminer.go
**Summary**
It is now best pratice to use the `%w` verb to wrap errors passed to `fmt.Errorf`.
Wrapping errors allows them to be unwrapped with `errors.Unwrap`, checked for with `errors.Is`, and extracted with `errors.As`.
Error wrapping was introduced in Go 1.13, more information: https://go.dev/blog/go1.13-errors
Fixes #13 
**Changes**
- Use `%w` instead of `%v` to wrap errors passed to `fmt.Errorf`
- Begin all errors with a lowercase letter, per https://go.dev/wiki/CodeReviewComments#error-strings
> Use '%w' verb in fmt.Errorf to wrap errors (fixes #13)

- e2e/network_test.go
- service/popm/popm.go
- service/popm/popm_test.go
**Summary**
We need a way to retry mining keystones if they fail, this provides a solution.
Fixes #7 
**Changes**
* keep buffer of 10 newest keystones known
* upon receiving a keystone, only insert into buffer if it is newer than the oldest keystone
* if buffer is full, drop oldest keystone upon inserting another
* when a keystone is mined, mark it as "processed" to not repeat mining same keystone
* generate fewer btc blocks in full network e2e test, since we have a retry strategy now 
* remove retry from full network e2e test
> retry mine keystone on failure

- e2e/docker-compose.yml
- e2e/network_test.go
**Summary**
Sync ElectrumX environment variables in E2E with infra.
After merging #26 (c5b0fea01e84c7927c601a90a2046220434bbc7f), the electrumx client in BFG started being rate limited by ElectrumX during network tests, which would cause block processing to be significantly slower and cause the network test to timeout.
These environment variables remove the hard/soft (`COST_{HARD,SOFT}_LIMIT`) limits and increases the maximum size of response messages to 8 MiB (`MAX_SEND`).
Fixes #35 
**Changes**
- Sync ElectrumX environment variables with those used in production.
> e2e: sync ElectrumX environment variables with infra

- api/protocol/protocol.go
- cmd/bfgd/bfgd.go
- cmd/bssd/bssd.go
- cmd/hemictl/hemictl.go
- cmd/popmd/popmd.go
- database/bfgd/postgres/postgres.go
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
- service/bss/bss.go
- service/popm/popm_test.go
- service/popm/prometheus.go
- web/popminer/popminer.go
**Summary**
Use `errors.Is` to compare errors, instead of using the `==` operator.
More information: https://pkg.go.dev/errors#Is
**Changes**
- Replace use of `==` for error comparisons with `errors.Is`
> Use 'errors.Is' to compare errors

- api/bfgapi/bfgapi.go
- api/bssapi/bssapi.go
**Summary**
Copy the commands map with `maps.Clone` before returning in `{bssapi,bfgapi}.APICommands()`
More information: https://pkg.go.dev/maps#Clone
**Changes**
- Use `maps.Clone(commands)` to clone the commands map before returning from `APICommands()`
> Use `maps.Clone(m)` to copy returned map in `APICommands()`

- api/tbcapi/tbcapi.go
- database/tbcd/level/level.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/websocket.go
**Summary**
added balance-by-address endpoint to tbc
**Changes**
added an endpoint to tbc that allows us to get a balance for a given address.  this address is one of the 5 supported: P2PKH, P2SH, P2WPKH, P2WSH, P2TR.
also updated test timing to make it run faster
fixes #42 
updated code to properly querying by key prefix
> added balance-by-address endpoint to tbc

- .gitignore
- Makefile
- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
**Summary**
Add last block metadata API to tbcd
Fixes #39 
**Changes**
- Add `BlockHeadersBest(ctx)` function to tbc server
- Add `tbcapi-blockheaders-best-{request,response}` to tbcapi
- Add tbc temporary test files to the `.gitignore` file and `make clean`
- Add `omitempty` to errors in responses in tbcapi
- Remove unnecessary function names from error strings
> tbcapi: add blockheaders-best API and RPC

- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc_test.go
**Summary**
Rename block-header-by-height to block-headers-by-height
Fixes #53 
**Changes**
- Rename `tbcapi-btc-block-header-by-height-{request,response}` to `tbcapi-btc-block-headers-by-height-{request,response}`
- Rename `BtcBlockHeaderByHeight{Request,Response}` to `BtcBlockheadersByHeight{Request,Response}`
> Rename block-header-by-height to block-headers-by-height

- api/api.go
- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc_test.go
**Summary**
Use `api.ByteSlice` instead of raw byte slices in `tbcapi` to encode bytes as hexadecimal strings.
**Changes**
- Use `api.ByteSlice` instead of `[]byte` in `tbcapi` package
> tbcapi: use api.ByteSlice to encode bytes as hex

- service/tbc/rpc.go
**Summary**
Remove use of `math/rand` package in `service/tbc/rpc.go`.
I believe the original code in `service/tbc/rpc.go` used `crypto/rand`, however it appears to have been changed in #46 and committed as bd5f7bc5bdd3fb475ae291f0cc10c34984dd2d76.
The `math/rand` package is deterministic and should never be used where security matters.
Go 1.22 introduced [`math/rand/v2`](https://pkg.go.dev/math/rand/v2), which aims to improve the current `math/rand` package. I think it would be nice if we could update the required version in `go.mod` to Go 1.22 so that we can use this package instead of `math/rand`.
**Changes**
- Use `crypto/rand` instead of `math/rand` package in `service/tbc/rpc.go`.
> tbc: remove use of math/rand from rpc.go

- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
**Summary**
As tbcd is a bitcoin-only indexer, the decision was made to drop unnecessary "btc" prefixes from the names in `tbcapi`.
Fixes #52 
**Changes**
- Remove remaining `btc` prefixes
- Rename `AddrBalance{Request,Response}` to `BalanceByAddress{Request,Response}` to match command ID
> tbcapi: remove remaining "btc" prefixes

- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc_test.go
**Summary**
separate tx-by-id endpoint in raw vs cooked
**Changes**
separated tx-by-id endpoint into two version: raw returning bytes, cooked returning wire.MsgTx
fixes #56
> separate tx-by-id endpoint in raw vs cooked

- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc_test.go
**Summary**
utxos-by-address raw vs cooked + tx-by-id cleanup
**Changes**
this commit addresses two things:
* splitting up utxos-by-address into raw-vs-cooked
* fixing tx-by-id to return the error that will also be in the response; this allows us to print the error when responding
fixes #60
> utxos-by-address raw vs cooked + tx-by-id cleanup

- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
**Summary**
Add `tbcapi-block-headers-by-height-raw-{request,response}` and convert existing command to respond with serialised data.
**Changes**
- Add `tbcapi-block-headers-by-height-raw-{request,response}`
- Convert existing `tbcapi-block-headers-by-height-response` to contain serialised data
> tbcapi: split block-headers-by-height into raw and serialised

- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
**Summary**
Rename the existing `tbcapi-block-headers-best` command to `tbcapi-block-headers-best-raw` and add `tbc-block-headers-best` which returns serialised data.
**Changes**
- Add `Server.RawBlockHeadersBest()` which returns the best block headers as raw bytes
- Rename previous `tbcapi-block-headers-best` to `tbcapi-block-headers-best-raw`
- Add `tbcapi-block-headers-best` which returns serialised data
- Clean up utility functions in `tbc_test.go` to improve readability and maintainability
- Add `-noonion` and `-listenonion=0` flags to bitcoind in tbc_test, which prevents bitcoind from attempting to connect to the Tor control port
- Use random hexadecimal encoded bytes as unique identifiers for bitcoind containers, which helps to further prevent container name collisions
- Clean up …
> tbcapi: split block-headers-best into raw and serialised

- e2e/optimism-stack.Dockerfile
**Summary**
op-geth now depends on heminetwork, which we have in optimism.  ensure that optimism is cloned before op-geth
**Changes**
update dockerfile to do the above
> updated build order of op-stack

- service/tbc/tbc.go
- ttl/ttl.go
- ttl/ttl_test.go
The ttl package can be used to conveniently timeout events. Essentially it is a map that has an expiration per key.
**Summary**
`tbc` needs to schedule events in the future such as ping responses. This pr adds a convenient package to timeout or cancel events. The pings are needed to more aggressively kill misbehaving connections.
**Changes**
> Add aggressive ping/pong to cull questionable connections.

- cmd/bfgd/bfgd.go
- cmd/bssd/bssd.go
- cmd/popmd/popmd.go
- cmd/tbcd/tbcd.go
**Summary**
Replace `os.Kill` with `syscall.SIGTERM` in `signal.Notify` calls.
[`os.Kill` is equal to `syscall.SIGKILL`](https://pkg.go.dev/os#pkg-constants:~:text=Kill%20%20%20%20%20%20Signal%20%3D%20syscall.SIGKILL)
SIGKILL cannot be caught on Unix-like systems.
SIGTERM is often used to request that an application terminate gracefully.
https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html
https://man.openbsd.org/signal
**Changes**
- Replace `os.Kill` (syscall.SIGKILL) with `syscall.SIGTERM` in signal handlers
> Replace os.Kill with syscall.SIGTERM in signal.Notify calls

- cmd/popmd/popmd.go
- service/popm/popm.go
This adds the environment variable POPM_STATIC_FEE which can be used to configure a specific fee level for the PoP Miner to use.
Longer-term, BFG needs an RPC method for getting current network fee levels.
> Added configurable fee-per-vB to PoP Miner

- service/tbc/tbc.go
- service/tbc/tbc_test.go
- ttl/ttl.go
- ttl/ttl_test.go
**Summary**
The pending block cache is scanned in various locations. Instead of scanning this makes the block expire using the ttl package and thus the code is more even driven and it locks less.
**Changes**
- Cope with the new ttl package for pings.
- Replace blockPeer map with ttl.
Fixes #84
> Track pending blocks with ttl package

- e2e/docker-compose.yml
**Summary**
Fix `e2e/docker-compose.yml` failing with `container e2e-op-node-1 has no healthcheck configured`.
op-proposer previously depended on op-node being in the condition "service_healthy", which will never be reached because op-node does not have any healthchecks configured.
Fixes #98 
**Changes**
- Replace op-node dependency condition in op-proposer with `service_started`
> e2e: fix op-proposer op-node dependency condition (fixes #98)

- e2e/docker-compose.yml
**Summary**
previously, if initialblocks started before bitcoind was listnening for connections, initialblocks would fail and not restart, thus not generating the initial blocks needed to run the network.
**Changes**
fix this by restarted it "on-failure", if it fails to connect, it will retry.
> restart initialblocks on-failure

- api/api.go
- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc_test.go
**Summary**
Use reverse byte order for hashes (tx ids, block ids and merkle root) serialised tbcapi request/responses.
Additionally, change `tbcapi` to consistently use pointers to structs for data in responses, preventing unwanted allocations and causes `null` to be returned instead of an empty object.
**Changes**
- Use reverse byte order for hashes in `tbcapi`
- Tidy up `wire.MsgTx` to `tbcapi.Tx` conversion function
- Consistently use pointers for data structs in `tbcapi` responses
> tbcapi: use reverse byte order for hashes in serialised, tidy up

- e2e/e2e_ext_test.go
- service/tbc/tbc_test.go
**Summary**
in tests we use nextPort to find the next open port on the test machine to listen on, this is fragile as it sometimes returns a port that isn't available.
**Changes**
ensure that we cannot connect to the port before we return it
hopefully preventing errors like [this](https://github.com/hemilabs/heminetwork/actions/runs/8838322805/job/24269182897#step:7:487)
> more robust nextPort

- Makefile
- database/bfgd/postgres/postgres.go
- e2e/e2e_ext_test.go
**Summary**
Add a target to the Makefile to run [Staticcheck](https://staticcheck.io/), a "state of the art linter for the Go programming language" that uses static analysis.
Additionally, fix several issues detected by Staticcheck in the bfgd postgres database.
**Changes**
- Add `staticcheck` and `staticcheck-deps` make tasks.
- Fix several loops that were unconditionally exited after a single interation in `database/bfgd/postgres/postgres.go` (SA4004).
- Fix bug in `AccessPublicKeyDelete` implementation that caused `database.NotFoundError` to be returned even when a key was found and deleted.
**Notes**
It would be nice to add Staticcheck to the `lint` target in the future, however it currently reports a lot of issues, thus doing this would cause builds to fail.
*Passes tests and E2E …
> bfgd: fix loops unconditionally exited after one interation (SA4004)

- e2e/e2e_ext_test.go
**Summary**
when we broadcast notifications for new l2 keystones, there is no guarantee when those broadcasts will be sent out since it is async.  we had a test that would create new keystones, then write an api rpc request, then wait for a response.  occasionally, the response would be the notifications for new l2 keystones that were created earlier in the tests.  
**Changes**
we can safely ignore those in this test.
fixes #110
> ignore l2 keystones notifications in tests

- database/tbcd/database.go
- database/tbcd/database_test.go
- database/tbcd/level/level.go
**Summary**
This was a leftover from when we switched the outpoint in the memory map. The `u` prefix is now explicitly added. This does indeed fix a bug where we were copying the first `u` in index 1 and dropping the last octet of the hash.
**Changes**
> Do not recreate outpoint for ScriptHashByOutpoint.

- database/bfgd/database_ext_test.go
- e2e/e2e_ext_test.go
**Summary**
Remove use of `io/ioutil` package, which is deprecated as of Go 1.16 (SA1019).
**Changes**
- Use `os.ReadFile` instead of `ioutil.ReadFile` in `database/bfgd/database_ext_test.go`
- Use `os.ReadFile` instead of `ioutil.ReadFile` in `e2e/e2e_ext_test.go`
> database,e2e: remove use of deprecated `io/ioutil` (SA1019)

- e2e/e2e_ext_test.go
**Summary**
Improve confusing constant name `mockElectrumxConnectTimeoutSeconds` (type `time.Duration`) by removing `Seconds`.
`time.Duration` values represent an amount of time in nanoseconds, therefore it is not appropriate to suffix a variable of type `time.Duration` with a time unit.
**Changes**
- Rename `mockElectrumxConnectTimeoutSeconds` to `mockElectrumxConnectTimeout` in `e2e`.
> e2e: improve name for variable with type `time.Duration` (ST1011)

- service/popm/popm_test.go
**Summary**
Use simple conversion instead of unneccesarily using `fmt.Sprintf` ([S1025](https://staticcheck.io/docs/checks#S1025))
**Changes**
- Use simple conversion instead of `fmt.Sprintf` to convert strings in popm.
> popm: use simple conversion instead of unnecessary fmt.Sprintf (S1025)

- service/popm/popm_test.go
**Summary**
Simplify `receivedKeystones` variable in PoP miner tests
**Changes**
- Directly assign `receivedKeystones` variable in `popm_test.go` instead of creating the variable and then adding each element in a `for range` loop.
> popm: simplify receivedKeystones variable in tests

- database/bfgd/postgres/postgres.go
- database/bfgd/scripts/0007.sql
**Summary**
prior, we were refreshing a materialized view on each l2_keystones insert/update.  this isn't needed as the materialized view doesn't use that table. 
**Changes**
remove that trigger.
> bfgd: drop btc_blocks_can refresh triggers for l2_keystones/pop_basis

- .github/workflows/release.yml
**Summary**
Use the `hemilabs` organisation-level `DOCKERHUB_TOKEN` secret.
Previously, a repository secret called `DOCKERHUB_PASSWORD` was used.
**Changes**
- Use `DOCKERHUB_TOKEN` secret instead of `DOCKERHUB_PASSWORD`
**Notes**
The existing `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD` secrets on this repository should be removed in favour of the organisation-level secrets.
> ci: use org DOCKERHUB_TOKEN secret

- .github/workflows/release.yml
**Summary**
Adds a missing `$` character that causes the version type to always be set to 'unstable' in the release workflow.
**Changes**
- Fix version type check in release workflow prepare step
> ci: fix bug that makes version type always 'unstable'

- service/popm/popm.go
**Summary**
Remove unused `handle` function and return previously unused err in `connectBFG`.
**Changes**
- Remove unused `handle` function
- Return previously unused `err` in `connectBFG` function (bug)
> popmd: remove unused 'handle' func and return err in connectBFG

- cmd/hemictl/hemictl.go
**Summary**
Simplify sorting string slice in hemictl.
**Changes**
- Use `sort.Strings(...)` instead of `sort.Sort(sort.StringSlice(...))` in hemictl package (S1032).
> hemictl: use sort.Strings(...) instead of sort.Sort(sort.StringSlice(...)) (S1032)

- hemi/electrumx/conn.go
- hemi/electrumx/conn_test.go
- hemi/electrumx/electrumx.go
**Summary**
Fix unhandled error from `json.Marshal` in `NewJSONRPCRequest` function.
**Changes**
- Add error return value to `NewJSONRPCRequest`
- Return error from `json.Marshal` error in `NewJSONRPCRequest`
- Handle errors from `NewJSONRPCRequest`
> electrumx: fix unhandled error in NewJSONRPCRequest

- e2e/e2e_ext_test.go
**Summary**
Fix issues reported by staticcheck for code in the `e2e` directory.
**Changes**
- Remove unused `wg` and `addr` fields from `bssWs`
- Remove unused `createPopm` function
- Fix ineffective break statements
- Rename variables prefixed with `_`
> e2e: fix issues detected by staticcheck

- database/bfgd/database.go
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
- database/bfgd/scripts/0008.sql
- service/bfg/bfg.go
**Summary**
in BFG, we only increment block height to get each block in the chain; if there is a fork, we don't handle for it.  
**Changes**
this introduces a check for blocks with no children, it will then "re-process" the block at that height from electrumx
fixes #130
> Stopgap to re-fetch blocks with no children

- service/tbc/tbc.go
**Summary**
localnet is small, and is easy for tbc to crawl and index.  with localnet, we often run it in CI environments where we have limited or no control over ulimits.  there is no need for this in localnet, so let's ignore it if we're on localnet.
**Changes**
if network set to localnet, ignore ulimits
> ignore ulimits in tbc when on localnet

- cmd/popmd/popmd.go
- web/Makefile
- web/popminer/api.go
- web/popminer/dispatch.go
- web/popminer/network.go
- web/popminer/network_local.go
- web/popminer/popminer.go
- web/popminer/util.go
- web/www/index.html
- web/www/index.js
- web/www/popminer.js
- web/www/wasm_exec.js
**Summary**
Initial pass to improve and tidy up the Go code for the WASM PoP Miner.
This is the first of many pull requests to improve the WASM and create a TypeScript (NPM) package that can be used to run the PoP Miner.
**Changes**
This splits the `web/popminer/popminer.go` file into 6 files:
- `api.go`: Contains all API types
- `dispatch.go`: Contains all methods that can be dispatched from JS.
The majority of the code in this file was moved from `popminer.go`.
- `network.go`: Contains Hemi/Bitcoin network settings
- `network_local.go`: Contains localnet settings (behind build tag, build with `-tags "hemi_localnet"` to enable)
- `popminer.go`: Contains the main function and core
- `util.go`: Contains utility functions for working with JS.
This contains a lot of miscellaneous …
> popm/wasm: improve and tidy up Go code

- cmd/tbcd/tbcd.go
- config/config.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
**Summary**
allow tbc seeds to be overwritten
**Changes**
if cfg seeds are set, use those, otherwise use the defaults for the network chosen
fixes #157
> tbc: allow seeds to be overwritten

- web/Makefile
**Summary**
Add `wasm-opt` target to `web/Makefile` that optimises the WASM binary output from the `wasm` target using `wasm-opt` from binaryen.
From testing, this seems to shrink the output binary's size by around 1M.
```
joshua@ringo web % du -hs webapp/popminer.wasm 
12M    webapp/popminer.wasm
joshua@ringo web % m wasm-opt
/opt/homebrew/bin/wasm-opt
wasm-opt -Oz /Users/joshua/Projects/hemilabs/heminetwork/web/webapp/popminer.wasm -o /Users/joshua/Projects/hemilabs/heminetwork/web/webapp/popminer.wasm.opt --enable-bulk-memory --intrinsic-lowering
mv /Users/joshua/Projects/hemilabs/heminetwork/web/webapp/popminer.wasm.opt /Users/joshua/Projects/hemilabs/heminetwork/web/webapp/popminer.wasm
joshua@ringo web % du -hs webapp/popminer.wasm 
11M    webapp/popminer.wasm
```
**Changes**
- Add …
> popm/wasm: add wasm-opt target to optimise wasm binary

- web/popminer/api.go
- web/popminer/dispatch.go
- web/popminer/util.go
- web/www/index.html
- web/www/index.js
**Summary**
Add error codes to the WebAssembly PoP Miner.
These error codes will be used to programatically handle errors and display useful information to users.
The default error code is ErrorCodeInternal ("internal").
**Changes**
- Add `ErrorCode` type and add `Code` field to the existing `Error` type
- Add `ErrorCodeInternal` for use with internal errors (and is the default error code)
- Add `ErrorCodeInvalidValue` for use when an invalid value is provided for an argument, currently only used in `generateKey`
- Refactor how some elements are displayed in integration test web page to help with testing
- Add `codedError` type, used to include an error code in an error that is extracted when creating an `Error` that will be converted to a JavaScript Object
More error codes will be added …
> popm/wasm: add error codes

- web/popminer/api.go
- web/popminer/util.go
**Summary**
Improve `js.Value` creation in the WebAssembly PoP Miner, add `JSMarshaler` interface.
**Changes**
- Refactor logic of `jsValueOf` and `jsValueSafe`
- Improve error logging when a value cannot be converted
- Add `JSMarshaler` interface which can be used to implement custom logic for converting a type into a `js.Value`
> popm/wasm: improve js.Value creation, add JSMarshaler interface

- .github/labeler.yml
- .github/workflows/labeler.yml
**Summary**
Add a GitHub Actions workflow that will automatically label pull requests based on the files modified by the pull request.
This should allow pull requests to be labeled more accurately, while reducing the amount of time required to update labels.
Uses https://github.com/actions/labeler. At a later date, it might be worth considering a third-party action that supports adding labels by age, size, etc.
**Changes**
- Add labeler workflow: `.github/workflows/labeler.yml`
- Add labeler config: `.github/labeler.yml`
> ci: add labeler action

- .github/CODEOWNERS
- scripts/release.sh
**Summary**
Add a _definitely not over engineered_ release script to easily and safely create and push git tags.
Tags the latest remote commit in the heminetwork repository's main branch and pushes the tag to the repository, triggering the release CI which will build all necessary binaries, Docker images, etc. and create a GitHub release.
This script will create a new remote called `upstream` (configurable with `REMOTE_NAME`). This remote is used to fetch the latest commit on the main branch, allowing a tag to be created on the latest remote commit while ignoring any local changes.
The provided version (and all version bumps) must follow the Semantic Versioning 2.0.0 specification (<major>.<minor>.<patch>), as per https://semver.org/. This allows the versioning to stay consistent while …
> scripts: add release script

- .github/workflows/release.yml
**Summary**
Add `registry-url` to `actions/setup-node` in release workflow.
This should fix the error that caused the last NPM release job to fail.
**Changes**
- Set `registry-url: "https://registry.npmjs.org"` when running `actions/setup-node` in the `.github/workflows/release.yml` workflow.
> ci: add registry-url to setup-node in release

- web/packages/pop-miner/src/browser/index.ts
- web/packages/pop-miner/src/browser/wasm.ts
- web/packages/pop-miner/src/types.ts
- web/popminer/api.go
- web/popminer/dispatch.go
- web/www/index.html
- web/www/index.js
**Summary**
Add a `parseKey` method to the WebAssembly PoP Miner and `@hemilabs/pop-miner` package that takes a network type and secp256k1 private key and returns the public key, Bitcoin address and public key hash, and the Ethereum address.
**Changes**
- Add `parseKey` method to the WebAssembly PoP Miner.
- Rename `GenerateKeyResult` to `KeyResult` in pop-miner package.
- Fix typo `secpk256k1` -> `secp256k1`.
> popm/wasm: add 'parseKey' method

- web/packages/pop-miner/src/browser/index.ts
- web/packages/pop-miner/src/browser/wasm.ts
- web/packages/pop-miner/src/types.ts
- web/popminer/api.go
- web/popminer/dispatch.go
- web/www/index.html
- web/www/index.js
**Summary**
Add a `bitcoinAddressToScriptHash` function to the WebAssembly PoP Miner and `@hemilabs/pop-miner` package that takes a network type and Bitcoin address and returns the script hash.
**Changes**
- Add `bitcoinAddressToScriptHash` to the WebAssembly PoP Miner.
> popm/wasm: add 'bitcoinAddressToScriptHash' method

- .github/workflows/go.yml
- .github/workflows/release.yml
- Makefile
**Summary**
This pull request aims to improve the runtime of "high usage CI workflows" (i.e. `go.yml` and parts of `release.yml`).
These CI workflows are rather slow, partially due to the amount of time certain tests are currently taking, but also due to the lack of correctly configured caching in some workflows.
The average runtime of the `go.yml` workflow is currently **365.9 seconds (6~ minutes)**.
The repository root `Makefile` changes the `GOCACHE` environment variable, resulting in Go writing the build cache to a directory stored within the repository (not in git), allowing for easy clean up with `make clean`.
This has some benefits, however none of them apply to CI environments. The `actions/setup-go` action has built-in support for caching installed Go mod dependencies, as well as …
> ci: improve runtime of high usage CI workflows

- web/popminer/dispatch.go
**Summary**
Use uncompressed serialised secp256k1 public key to create the Ethereum address.
Previously, the compressed serialised secp256k1 public key was used, which resulted in a different value being provided as the address.
**Changes**
- Use uncompressed serialised secp256k1 public key to create Ethereum addresses in the WebAssembly PoP Miner.
> popm/wasm: fix ethereum address when generating and parsing keys

- service/popm/event.go
- service/popm/popm.go
- web/packages/pop-miner/src/browser/index.ts
- web/packages/pop-miner/src/browser/wasm.ts
- web/packages/pop-miner/src/types.ts
- web/popminer/api.go
- web/popminer/dispatch.go
- web/popminer/popminer.go
- web/popminer/util.go
- web/www/index.html
- web/www/index.js
**Summary**
Add events to the PoP Miner and WebAssembly PoP Miner.
**Changes**
- Add events to `popm` and `Miner.RegisterEventHandler(EventHandler)`
- Add events to the WebAssembly PoP Miner and `@hemilabs/pop-miner` package
- Rename `activeMiner()` to `runningMiner()`
- Add a `Service` type and use `svc` global variable (replaces `pm` and `pmMtx`). This allows us to have a global struct to store data in, without the need to use a lock to access the data. The miner is now stored in a `miner` field, guarded by the `minerMtx` RWMutex. This service also contains the event listeners and the listeners map RWMutex.
- Add initial 4 events: `minerStart`, `minerStop`, `mineKeystone`, and `transactionBroadcast`.
> popm/wasm: add events and clean up globals

- web/packages/pop-miner/src/types.ts
- web/popminer/api.go
- web/popminer/dispatch.go
**Summary**
Rename fields in `KeyResult` and add `bitcoinScriptHash` field.
Resolves #176 
**Changes**
- Rename `ethereumAddress` to `hemiAddress`
- Rename `publicKeyHash` to `bitcoinPubKeyHash`
- Add `bitcoinScriptHash` containing the Bitcoin pay-to-pubkey-hash script for the secp256k1 key.
> popm/wasm: rename KeyResult fields and add bitcoinScriptHash

- service/popm/popm.go
- web/packages/pop-miner/src/browser/index.ts
- web/packages/pop-miner/src/browser/wasm.ts
- web/packages/pop-miner/src/types.ts
- web/popminer/api.go
- web/popminer/dispatch.go
- web/popminer/util.go
- web/www/index.html
- web/www/index.js
**Summary**
Add a `minerStatus` method to the WebAssembly PoP miner that exposes the whether the miner is running, and whether the miner is currently connected to the BFG server.
Closes #171 
**Changes**
- Add `minerStatus` method to the WebAssembly PoP miner and `@hemilabs/pop-miner` package
- Add `Connected()` function to the PoP miner that returns whether the miner is currently connected to BFG
- Add `readonly` to event fields in `@hemilabs/pop-miner` package
> popm/wasm: add 'minerStatus' method

- web/packages/pop-miner/src/browser/index.ts
**Summary**
Fix dispatch params for `addEventListener` and `removeEventListener` in the `@hemilabs/pop-miner` package.
**Changes**
- Change `listener` param to `handler` in the `addEventListener` and `removeEventListener` functions in the pop-miner NPM package.
> popm/wasm: fix dispatch params for {add,remove}EventListener

- go.mod
- go.sum
- service/popm/popm.go
- service/popm/popm_test.go
**Summary**
Avoid "dust" errors when broadcasting PoP transactions to Bitcoin by checking if the transaction output would be considered dust with a relay tx fee of 10,000.
If the transaction output would be considered dust, then don't include the output and instead leave the remaining to be included as a fee.
Fixes #183 
**Changes**
- Don't add a change transaction output when creating a transaction if the transaction output is dust.
> popm: exclude tx outputs that would be dust

- hemi/electrumx/conn.go
- hemi/electrumx/conn_test.go
**Summary**
Fix a panic in the ElectrumX client caused by attempting to close the `closeCh` channel twice.
This happened when the `pinger` goroutine attempted to close the connect when the connection had already been closed.
Additionally, add a wait group to the ElectrumX connection struct that is used to wait for the pinger goroutine to exit before returning in the `Close` function, making sure that we don't leak the goroutine and everything gets properly shutdown.
Fixes #191
**Changes**
- Fix `closeCh` channel being closed more than once.
- Add wait group to `clientConn` that is used to wait for the `pinger` goroutine to exit in the `Close` function.
- Close the `closeCh` channel after the underlying connection has been closed.
- Add test for closing `clientConn`s.
> electrumx: improve closing and fix close panic

- api/auth/secp256k1_test.go
- api/protocol/protocol.go
- service/bss/bss.go
- service/popm/popm.go
**Summary**
Increase the read limit in BSS for the BFG connection to 2 MiB (previously 512 KiB).
When there is a lot of active PoP Miners broadcasting transactions, the `pop-txs-for-l2-block` response from BFG becomes too large for BSS to read. This increases the read limit to temporarily avoid this problem.
Related to: https://github.com/hemilabs/heminetwork/issues/193
**Changes**
- Add `protocol.ConnOptions` which can be used to provide options when creating a `protocol.Conn`.
- Increase the BSS -> BFG connection read limit to 2 MiB (previously 512 KiB).
> bss: increase read limit for bfg conn to 2 MiB

- service/tbc/rpc_test.go
**Summary**
lastErr was added to handle for something that likely shouldn't have been; it's an un-needed way to handle for errors.  replace with simply failing the test if there are errors.
**Changes**
remove lastErr variables from rpc_test.go
fixes #182
> remove lastErr variables from rpc_test.go

- service/popm/popm.go
**Summary**
Reword BFG reconnect log and decrease log level to "info".
This probably should not have been "error" in the first place, as it is more informational, and this was resulting in false bug reports from users.
**Changes**
- Improve BFG reconnect log in PoP Miner
> popm: change BFG reconnect log to 'info' level

- cmd/hemictl/hemictl.go
- cmd/tbcd/tbcd.go
- database/database.go
- database/tbcd/database.go
- database/tbcd/level/level.go
- go.mod
- go.sum
- service/tbc/peer_manager.go
- service/tbc/tbc.go
- service/tbc/tbcfork_test.go
**Summary**
Unwinding a chain is quite expensive when measured in block and header lookups. Often repeating the same process. This creates a cache for both. Note that the header cache is only primed during reads; this is deliberate because the cost of generating the cache entries is too high in the write path.
It tries to keep the block cache at 1GB and the header cache at 100MB.
**Changes**
> Add a header and block cache.

- cmd/btctool/btctool.go
- cmd/hemictl/hemictl.go
- database/tbcd/database.go
- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/rpc_test.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
**Summary**
We are doing all kinds of gymnastics to convert to and from arrays, byte slices and chainhash. Promote chainhash to a main type and propagate it through the stack. This vastly simplifies the code and makes it more readable. This will unfortunately break a bunch of callers but they'll have to cop.
**Changes**
> Move various arrays and byte slices to use pointers to chainhash.

- hemi/electrumx/electrumx.go
**Summary**
Retry `syscall.EPIPE` ("broken pipe") errors in the ElectrumX client.
This will use a new client from the pool, which _should_ resolve the error.
**Changes**
- Retry `syscall.EPIPE` ("broken pipe") in electrumx client
> electrumx: retry broken pipe error

- database/bfgd/database.go
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
**Summary**
Counting `l2_keystones` is only used in tests, there is no need for it to be a public function.
**Changes**
remove the public function `L2KeystonesCount`
> remove L2KeystonesCount from being a public function

- hemi/electrumx/conn_pool.go
**Summary**
Set `p.pool` to return value of `slices.DeleteFunc` when removing a connection. 
As of go1.23, `go vet` reports this issue: https://go-review.googlesource.com/c/tools/+/554317
The item is still removed from the slice, however the length of the slice is not updated. See implementation of `slices.DeleteFunc`:
```go
clear(s[i:]) // zero/nil out the obsolete elements, for GC
return s[:i]
```
This has likely been causing errors with the pool, such as connections not being returned and instead being closed, as well as the size being returned wrong.
**Changes**
- Set `p.pool` to return value of `slices.DeleteFunc` when removing a connection.
> electrumx: fix removing conn from pool

- cmd/extool/extool.go
- docker/bfgd/Dockerfile
- docker/bssd/Dockerfile
- docker/popmd/Dockerfile
- hemi/electrumx/conn.go
- hemi/electrumx/conn_pool.go
- hemi/electrumx/conn_pool_test.go
- hemi/electrumx/conn_test.go
- hemi/electrumx/electrumx.go
- service/bfg/bfg.go
**Summary**
Add prometheus metrics to the ElectrumX client and connection pool in BFG.
- `bfg_electrumx_connections_open` - Number of open ElectrumX connections
- `bfg_electrumx_connections_idle` - Number of ElectrumX connections in the pool
- `bfg_electrumx_connections_opened_total` - Total number of ElectrumX connections opened
- `bfg_electrumx_connections_closed_total` - Total number of ElectrumX connections closed
- `bfg_electrumx_rpc_calls_total` - Total number of ElectrumX RPC calls
- `bfg_electrumx_rpc_calls_duration_seconds` - ElectrumX RPC call durations in seconds
**Changes**
- Add metrics to Electrumx client, connection pool and connection.
- Use a struct for electrumx client options: `electrumx.ClientOptions`.
- Only copy `Makefile`, `go.mod` and `go.sum` to run `make deps` in …
> electrumx,bfg: add electrumx prometheus metrics

- database/bfgd/database.go
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
- database/bfgd/scripts/0009.sql
- database/postgres/postgres.go
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
- service/bss/bss.go
**Summary**
Add a system with a static number of workers to queue/consume bitcoin broadcasts to electrumx
**Changes**
add a db table btc_transaction_broadcast_request that will store broadcast requests.  when someone wants to broadcast a tx, insert into this table (ignoring duplicates).  have a few workers that read from this table and attempt to broadcast transactions to electrumx.
when a worker "checks out" a broadcast request, it updates the last_broadcast_attempt_at column
when a worker confirms a broadcast, it updates the broadcast_at column
wait a random number of  minutes between 1-5 before processing same tx again if not confirmed
don't process txs that are more than 30 minutes hours old
caching l2 keystones response
more efficient finality query
> add queuing system for bitcoin broadcasts

- .goreleaser.yaml
**Summary**
Fix repository name in GoReleaser config (`hemilabs/network` -> `hemilabs/heminetwork`).
**Changes**
- Change `release.github.name` to `heminetwork` in `.goreleaser.yaml`.
> goreleaser: fix typo in release repo name

- e2e/e2e_ext_test.go
**Summary**
We updated recent l2 keystones to grab off of an async-refreshed cache, ensure this cache has time to update in tests that I had previously missed
**Changes**
added needed test waits since recent l2 keystones are updated async
> added needed test waits since recent l2 keystones are updated async

- .github/workflows/go.yml
- .github/workflows/localnet-test.yml
- .github/workflows/node.yml
- .github/workflows/release.yml
- README.md
- cmd/tbcd/README.md
- docker/bfgd/Dockerfile
- docker/bssd/Dockerfile
- docker/popmd/Dockerfile
- e2e/monitor/README.md
- e2e/monitor/go.mod
- e2e/optimism-stack.Dockerfile
- go.mod
**Summary**
Build project with [Go v1.23](https://tip.golang.org/doc/go1.23).
This does not change the `go` directive in the `go.mod` files, meaning we do not require consumers of this module to use `go1.23`, and we cannot use Go v1.23 features yet.
**Changes**
- Use toolchain `go1.23`
- Use Go `1.23.x` in GitHub Actions
- Update Go Docker images to `1.23-alpine3.20` and `1.23-bookworm` (debian)
- Document that Go 1.23 is required for building (previously 1.22.2 or newer)
*Note: Go v1.23 introduces new `go vet` checks for the `slices` package which are currently failing, resolved by #215*
> all: build with go1.23

- e2e/e2e_ext_test.go
- service/bfg/bfg.go
**Summary**
As of now, each time pop miner wants to mine they call `bfgapi.BitcoinInfoRequest` to get the height.  Bitcoin height doesn't change that often (not enough to be reaching out to the client in _every single request_ at least).  
We have another goroutine that gets the height on a 5 second timer; piggy-back off of this to set a server-value of the btc height from the last success in this goroutine.  This way, clients (i.e. pop miners) don't make a call to electrumx when getting bitcoin info. 
**Changes**
use the result of another go routine's `btcClient.Height` to set a cached height value.
this would be at most 5 seconds out-of-sync with electrumx
> cache bitcoin height from process btc block

- e2e/e2e_ext_test.go
- service/bfg/bfg.go
we (potentially) insert pop_basis twice, once when broadcasting, another when parsing btc blocks.  we don't need the former at this point, remove it so we take stress off of the db.
**Summary**
we (potentially) insert pop_basis twice, once when broadcasting, another when parsing btc blocks.  we don't need the former at this point
**Changes**
remove the first insert so we take stress off of the db
> remove insertion of pop_basis during broadcast

- hemi/electrumx/conn_pool.go
**Summary**
Fix ElectrumX connection pool open/closed/idle metrics.
Previously, the `open` metric and `closed_total` metrics weren't handled properly when a connection is closed.
They would only be changed if the connection was also removed from the connection pool, which is false in most cases.
Additionally, the `connsIdle` metric needs to be decremented when a connection in the pool is removed and closed.
**Changes**
- Decrement connsIdle if a connection is removed from the pool in onClose.
- Always decrement connsOpen when a connection is closed.
- Always increment connsClosed when a connection is closed.
> electrumx: fix open/closed/idle metrics for conn pool

- service/popm/popm.go
- service/popm/popm_test.go
- web/packages/pop-miner/src/types.ts
- web/popminer/api.go
- web/popminer/dispatch.go
- web/popminer/fee.go
- web/popminer/network.go
- web/popminer/popminer.go
- web/www/index.html
- web/www/index.js
**Summary**
Add an automatic fee system to the WASM PoP Miner.
When enabled, the recommended fees are fetched from mempool.space's REST API.
Fees are re-fetched at a configured interval (default 5 minutes). The `economyFee` value will be used by default, however this can be configured with by setting `automaticFees` to a `RecommendedFeeType` value (`fastest`, `halfHour`, `hour`, `economy`, `minimum`).
**Changes**
- Add ability to change fees during runtime in the PoP Miner (`(*Miner).Fee() uint` and `(*Miner).SetFee(uint)`).
- Add `automaticFees?: boolean | RecommendedFeeType` and `automaticFeeRefreshSeconds?: number` to `MinerStartArgs`.
- Add `fee: number` to `MinerStatusResult`.
> popm/wasm: add automatic fees

- Makefile
- api/tbcapi/tbcapi.go
- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/rpc.go
- service/tbc/rpc_test.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
**Summary**
Add `tbcapi-block-by-hash` and `tbcapi-block-by-hash-raw` commands to TBC RPC.
Additionally, use `chainhash.Hash` for all hashes in RPC.
Closes #219
**Changes**
- Add `tbcapi-block-by-hash` and `tbcapi-block-by-hash-raw` commands to TBC RPC, these commands can be used to retrieve blocks by their hash.
- Use `chainhash.Hash` instead of `api.ByteSlice` for hashes in RPC. **This is a breaking change. Raw RPC calls must now provide hashes in display-order as well.**
- Capitalise `Utxo` as `UTXO` consistently in the `tbcapi` package. Initialisms should be all uppercase, per https://go.dev/wiki/CodeReviewComments#initialisms
> tbc: add block-by-hash command to RPC, use chainhash

- database/bfgd/postgres/postgres.go
**Summary**
prior, when selecting a row to update, we were not locking the row selected so multiple processes could get this row at the same time.
**Changes**
select row `FOR UPDATE` to lock row to ensure only one process gets it
> need to select FOR UPDATE to lock row

- database/bfgd/database.go
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
- database/bfgd/scripts/0010.sql
- service/bfg/bfg.go
**Summary**
trim queue items older than an hour
add index for retries, using sorted `created_at`
**Changes**
trim queue items older than an hour
add index for retries, using sorted `created_at`
> trim old, new index

- hemi/electrumx/conn.go
- hemi/electrumx/conn_test.go
**Summary**
Fix deadlock when an ElectrumX connection pinger calls `(*clientConn).Close()`, discovered by @ClaytonNorthey92.
Close previously waited on the pinger to exit before setting `closeCh = nil`, so that `closeCh != nil` could be checked to prevent panics by closing the channel more than once. This resulted in a deadlock when Close was called inside the `pinger` goroutine.
Instead of using the `closeCh` channel, use a cancelable context stored in the `clientConn` struct. This isn't the best approach, but is simple and doesn't have double close issues. This also allows us to use this context when pinging ElectrumX, allowing the ping to be canceled when the connection is closed.
Additionally, this stops the ticker used in the `pinger` goroutine. Failing to stop `time.Ticker`s prior …
> electrumx: fix deadlock in Close/pinger, stop ticker

- service/bfg/bfg.go
**Summary**
Fix a couple issues reported by Staticcheck in BFG.
**Changes**
- Fix order of arguments in call to `errors.Is` in `processBitcoinBlock`, the correct order is `(err, target)` (SA1032).
- Omit nil check for `v.publicKey` in `handleAccessPublicKeys`, as `len(nilSlice)` is zero (S1009).
> bfg: fix issues reported by staticcheck

- web/popminer/dispatch.go
**Summary**
The documentation for `@hemilabs/pop-miner` states that `automaticFees` defaults to `true`:
```typescript
/**
* Whether to do automatic fee estimation using the mempool.space API.
* Defaults to true. If disabled, then only the staticFee will be used.
*
* When the value is true, the 'economy' recommended fee type will be used.
*/
automaticFees?: boolean | RecommendedFeeType;
```
This makes the code behave as documented.
**Changes**
- Enable automatic fees in the WebAssembly PoP Miner when `automaticFees` is `undefined`.
> popm/wasm: make automaticFees default to enabled

- database/bfgd/postgres/postgres.go
**Summary**
When getting the "effective height", we were not bounding the possible heights, this causes the query to scan over an entire index until it finds a height that is satisfactory to the rest of the query.
We use "effective height" in our "finality" calculation:
Finality = Min(100, (Canonical Tip Height - Effective Height - 9 + 1))
Since Finality cannot be more than 100, it is futile to look for an effective height that would be >= 100 blocks from the tip.
So we should only be concerned with effective heights >= tip - 100.
**Changes**
Bound the effective height calculation to 100 blocks from the tip to ensure that we don't scan over needless parts of the height index.
**Important Note:** if no results are returned, then the effective height gets "coalesced" to 0 which would result …
> bound height to 100 from canonical tip as to not have to scan large portion of index

- database/bfgd/postgres/postgres.go
- database/tbcd/database.go
- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/peer.go
- service/tbc/rpc.go
- service/tbc/rpc_test.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
- ttl/ttl.go
- ttl/ttl_test.go
**Summary**
During runtime we quiesce p2p when indexing to prevent index corruption. When tbc unquiesces several p2p commands may have happened, including a forking event, which wasn't tracked. When tbc tries to recover it may end up with a chain geometry it currently cannot process.
**Changes**
- Remove index flag and overload that into the quiesce flag
- Add a function that can determine the common ancestor between two blocks.
- Add a function that determines the current chain state and unwinds indexes to a common ancestor and then winds them back to tip.
> Add mechanism to recover from forks at runtime

- web/packages/pop-miner/src/browser/index.ts
- web/packages/pop-miner/src/types.ts
- web/popminer/dispatch.go
- web/popminer/fee.go
- web/www/index.html
- web/www/index.js
**Summary**
Add `automaticFeeMultiplier` parameter to `MinerStartArgs` in the WebAssembly PoP Miner.
This allows the used fee to be increased or decreased by a percentage. For example, if the recommended fee returned by the `mempool.space` API is `500`, and the multiplier is set to `1.1`, the output fee will be `550` sats/vB.
**Changes**
- Add `automaticFeeMultiplier?: number` to `MinerStartArgs` (defaults to `1.1`, +10%).
- Make `automaticFees: true` use the `fastest` recommended fee by default.
- Add range check for `automaticFeeRefreshSeconds` (if set, must be greater than zero).
> popm/wasm: add automatic fee multiplier, fix auto fee args

- service/tbc/tbc.go
**Summary**
Fix use of `%w` formatting verb in `log.Errorf` in TBC.
**Changes**
- Replace `%w` with `%v` in `log.Errorf` call.
> tbc: fix log using %w verb

- service/bfg/bfg.go
**Summary**
when debugging by looking through logs, it's useful to be able to associate a log with a tx id, we currently don't do this on broadcast errors
**Changes**
add tx id to broadcast error
> add tx id to broadcast error log so we can trace it

- hemi/electrumx/conn.go
- hemi/electrumx/conn_pool.go
**Summary**
Move ElectrumX connection metric handling (`connections_opened`, `connections_open`, `connections_closed`) into the individual connection handling code.
This aims to fix an inconsistency where if multiple attempts are made to close a connection, `connections_open` can be decremented multiple times for the one connection, causing the number to potentially be lower than the real number (and possibly negative).
**Changes**
- Move handling for ElectrumX metrics `connections_opened`, `connections_open` and `connections_closed` to the `clientConn` struct in `conn.go`.
- Set `(*clientConn).conn` to `nil` when `(*clientConn).Close()` is called and the connection has been closed, preventing attempts to close the connection multiple times (`net.ErrClosed` will be returned).
- Return …
> electrumx: move conn metrics into clientConn

- api/bfgapi/bfgapi.go
**Summary**
Remove an additional slash from the default URLs in `bfgapi`.
Fixes #260 reported by @NorthernWinter.
**Changes**
- Remove an additional slash from the default URLs in `bfgapi`.
> bfgapi: remove additional slash from default urls (fix #260)

- service/tbc/crawler.go
**Summary**
Sometimes copy paste goes wrong...
**Changes**
Opportunistically add the indexer keys instead of relying on them being set upon first invocation of the indexer function.
> Opportunistically add indexer keys to db.

- service/popm/popm.go
- service/popm/popm_test.go
**Summary**
if we get multiple keystones before we mine one, there is a chance that keystones get queued up twice; we copy the known keystones on each reception, then we try to mine, but we only lock during the copying step, so keystones may be copied twice in two different go routines then mined
don't mine known keystones in goroutines, it isn't helping
use less than comparison in tests, if an rpc gets called more than the expected number of times, this is ok
add consistent (longer) timeout to tests
**Changes**
see above
> stability and fragile test fixes

- README.md
- cmd/bfgd/bfgd.go
- cmd/extool/extool.go
- e2e/cookie
- e2e/docker-compose.yml
- e2e/e2e_ext_test.go
- e2e/monitor/main_test.go
- hemi/electrs/conn.go
- hemi/electrs/conn_pool.go
- hemi/electrs/conn_pool_test.go
- hemi/electrs/conn_test.go
- hemi/electrs/electrs.go
- service/bfg/bfg.go
**Summary**
We want to replace electrumx with electrs, here is how we can do it in heminetwork.
**Changes**
* update rpc interface to implement electrs rpc; the main thing here is that parameters are now passed in based on their position, rather than json object key/value pairings
* replace "electrumx" with "electrs" in source code
* update localnet to use electrs
> Replace electrumx with electrs

- api/bfgapi/bfgapi.go
- api/bssapi/bssapi.go
- database/bfgd/database.go
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
- service/bss/bss.go
**Summary**
allowing pagination of flow bss.popPayouts --> bfg.popTxsForL2Block
**Changes**
added pagination to aforementioned logical path
**IMPORTANT: optimism will need to be updated to include pagination otherwise this will limit request to 100 results**
fixes #195
> bfg,bss: add pagination to PoP txs and payouts

- api/bfgapi/bfgapi.go
- cmd/popmd/popmd.go
- config/config.go
- service/popm/popm.go
**Summary**
Make the BFG request timeout in the PoP miner configurable, and increase the default to 15 seconds.
It is configurable in BFG as well, the default has been changed to 10 seconds (previously 9).
This should help increase the number of successful requests. More BFG-side changes will be in follow-up PRs.
**Changes**
- Add `POPM_BFG_REQUEST_TIMEOUT` environment variable to popmd
- Increase the default PoP Miner BFG request timeout to 15 seconds
- Increase the default BFG request timeout to 10 seconds
> popmd: make BFG request timeout configurable

- e2e/docker-compose.yml
- e2e/e2e_ext_test.go
- hemi/electrs/conn.go
- hemi/electrs/electrs.go
**Summary**
we want to try out blockstream's electrs as opposed to the community one, this allows us to do so
**Changes**
make bfg compatible with blockstream's electrs
update localnet
> Blockstream Electrs

- cmd/tbcd/tbcd.go
- database/tbcd/database.go
- database/tbcd/level/headercache.go
- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/tbc.go
**Summary**
LRU is too expensive to keep track of hundreds-of-thousands, and certainly too expensive for millions of entries.
**Changes**
This PR replaces the blockheader cache with a simple map. It uses a low-iq eviction strategy that basically is just random. It also lifts the block header cache for testnet3 to 3.5M items which may prove to be too expensive. It roughly translates to 4.5G at runtime if fully used. Mainnet uses about 1G.
> tbcd: revisit block header cache

- cmd/tbcd/tbcd.go
- go.mod
- service/tbc/crawler.go
- service/tbc/peer.go
- service/tbc/peer_manager.go
- service/tbc/peermanager_test.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
**Summary**
Peer manager is currently a turd because it was part of the server struct and got adulterated over time.
**Changes**
Clean up this mess by making it a full citizen.
Fixes #214
> tbcd: clean up peer and peermanager

- service/tbc/peer_manager.go
- service/tbc/tbc.go
Go's ReadDealine has surprising side effects that caused a functional connection to be terminated prior to actually expiring. By setting the ReadDeadline to 0 the peer read never times out. This is ok because there are a bunch of other commands being written that will cause the read to fail if they do not complete. Simply rely on the chatter to cause a connection close instead of trying to be clever and detect which error type the close path received.
**Summary**
**Changes**
> Fix disconnects caused by ReadDeadline.

- api/bfgapi/bfgapi.go
- api/protocol/protocol.go
- service/popm/popm.go
- service/popm/popm_test.go
**Summary**
Remove (very expensive) redundant `bitcoinBalance` API call from `mineKeystone`. The result of this API call is logged at the `trace` level, and is not necessary.
Additionally, this includes a few performance improvements for `bfgapi` and `protocol`:
- In `bfgapi`, instead of creating a new `&bfgAPI{}` when reading or writing a message, have one global `bfgAPI` instance which is reused.
- In `bfgapi`, make `APICommands()` return the map directly instead of cloning it.
- In `protocol`, avoid marshaling -> unmarshaling -> marshaling -> marshaling when writing every message. This was done to avoid having `null` arrays in JSON, which some languages *cough JavaScript* don't handle very well, and is not needed here.
> api,popmd: improve perf and remove redundant bitcoinBalance call

- service/tbc/crawler.go
- service/tbc/tbc.go
> Bring back mempool and sundry fixes.

- service/tbc/peer.go
- service/tbc/tbc.go
> Missed this commit

- version/version.go
**Summary**
Update the version variables in the `version` package to version v0.5.1.
Ideally we should keep these variables set to the next planned version, so that development binaries always have the next planned version.
GoReleaser will always change these in release binaries, so this only affects binaries not built with GoReleaser.
**Changes**
- Change `version.Minor` to `5`.
- Change `version.Patch` to `1`.
> version: bump version to 0.5.1

- e2e/docker-compose.yml
- e2e/monitor/main.go
- e2e/monitor/main_test.go
**Summary**
make localnet tests more robust
prior, localnet would wait a certain period of time, then check if we reached certain values of different resoruces in our local chain (ex. HEMI balance, pop txs mined).  this was problematic because there was no guarantee that we would reach those within the given amount of time for various reasons.
we could simply increase the time we wait, but then we would have to wait that amount of time per test.
**Changes**
now, set a max timeout of 10 minutes for the test + 2 minute warm up.  poll the network every 10 seconds for values reaching a reasonable threshold.  if we reach this threshold within the timeout, success! otherwise failure.
> make localnet tests more robust

- e2e/docker-compose.yml
- e2e/monitor/main.go
The l1 runs geth, not op-geth.
> Corrent container name in e2e tests

- database/database.go
- database/database_test.go
- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/tbc.go
- service/tbc/tbcfork_test.go
> Try to prevent header download stalls.

- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
When TBC is used inside other services we may need to insert blocks. The use case is an op-geth that has seen a block in the past yet tbc does not know it because it isn't canonical. Now that block may be needed for an index since it *was* canonical at some point in the past. It's a bit of a hack but there is no harm in having blocks sitting in the database that have been reorged out.
> Add InsertBlock RPC

- go.mod
**Summary**
Use Go 1.23.3 as the toolchain in `go.mod`.
**Changes**
- Change toolchain in `go.mod` to `go1.23.3`.
> go.mod: use toolchain go1.23.3

- e2e/e2e_ext_test.go
- go.mod
- service/tbc/tbc.go
- service/tbc/tbc_test.go
**Summary**
fragile test fixes, including random port for test bitcoind
**Changes**
fix a fragile test by filtering out incorrect commands, rather than failing on the first incorrect.  we get notifications this way, so it is sometimes expected to get a "notification".
also, expose bitoind on random ports during tests for tbc to avoid port collisions
> fragile test fixes + random bitcoind port during tests

- README.md
- cmd/bfgd/bfgd.go
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
- service/bfg/bfg_test.go
**Summary**
We want to make BFGs easier to run.  This PR will do so by allow a BFG (ex. run by a PoP miner) to receive l2 keystones from another, trusted BFG (example Hemi Labs) and use a local Electrs+bitcoind to broadcast the transaction instead of Hemi Labs (or any third party).  This will avoid congestion during: btc balance retrieval, btc utxos retrieval, btc height retrieval, and btc broadcasting.
fixes #261 
**Changes**
allow a BFG to connect to another BFG.  the client BFG will receive L2 Keystone notifications via the public websocket endpoint, it will then query for new keystones when it gets a notification.
you must use BFG_BFG_URL + BFG_BTC_PRIVKEY to connect to another BFG.
BFG will request the latest 3 keystones upon each notification then save them in the DB and broadcast …
> Allow connection of BFG to another BFG for L2 Keystone Notifications/Querying

- service/tbc/crawler.go
**Summary**
Fix incorrect error handling in crawler synchronization methods.
**Changes**
- Changed `if err == nil` to `if err != nil` in `SyncIndexersToHash` to correctly return errors.
- Made the same change in `syncIndexersToBest`.
> tbc: fix err logging in sync indexers

- Makefile
**Summary**
Improve the order of the targets run by 'all', to improve error readability (prefer build errors from go build instead of golangci-lint), and performance by running build to refresh the cache before running test/install.
**Changes**
- Change Makefile `all` target to run: `tidy build lint test install`. Previously: `lint tidy test build install`.
> make: improve all target order

- version/version.go
**Summary**
Prepare to release v0.6.0.
**Changes**
- Bump version constants to represent v0.6.0.
> version: bump to 0.6.0

- database/bfgd/postgres/postgres.go
- database/bfgd/scripts/0011.sql
add index to pop_basis so we can avoid "rescans" in the query
**Summary**
rescans were taking a long time in the pop tx query, add an index to avoid them. 
**Changes**
_Note:_ I call my index `clayton_tmp_0` for testing purposes, I have removed this indexed and renamed it in the PR.
before (for about 6-7k rows matching the `pop_basis` query)
```
Limit  (cost=26902.86..26903.11 rows=100 width=1321) (actual time=1979.313..1979.328 rows=100 loops=1)
InitPlan 1 (returns $0)
->  Limit  (cost=8.69..8.86 rows=1 width=41) (actual time=0.084..0.085 rows=1 loops=1)
->  Index Scan Backward using l2_keystone_l2_block_number_idx on l2_keystones  (cost=0.28..1175.82 rows=6989 width=41) (actual time=0.044..0.083 rows=51 loops=1)
->  Sort  (cost=26894.00..26911.03 rows=6811 width=1321) (actual …
```
> add index to pop_basis for pop tx queries

- cmd/tbcd/tbcd.go
- service/tbc/crawler.go
- service/tbc/prometheushorror.go
- service/tbc/tbc.go
**Summary**
Add a new prometheus gauge type that can carry labels so that we can expose strings when needed. Also make sure we can set the prometheus subsystem name so that an app can embed multiple tbc structs (hello op-geth!).
**Changes**
> Add additional prometheus capability to integrate in grafana

- api/tbcapi/README.md
> tbcapi: fix typo in docs readme

- .golangci.yaml
- Makefile
**Summary**
Fix copyright header linting in golangci-lint. The previous config expected the YEAR variable to always be the current year, instead of the last modification year.
This now expects the copyright year to be either the year the file was last modified in (e.g. `2024`), or a range of years up-to the year the file was last modified in (e.g. `2024-2025`).
**Changes**
- Match copyright year against `(\\d{4}-{{MOD-YEAR}})|({{MOD-YEAR}})` (where `{{MOD-YEAR}}` is replaced with the modification year of the file) in goheader linter.
> golangci: fix copyright header linting

- .golangci.yaml
- Makefile
- README.md
- service/tbc/crawler.go
- service/tbc/mempool.go
- service/tbc/tbc.go
**Summary**
We are seeing some performance issues with unwind and mempool certainly would not help so disable it really hard for now.
**Changes**
> Really really disable mempool

- cmd/tbcd/tbcd.go
- database/tbcd/database.go
- database/tbcd/level/blockcache.go
- database/tbcd/level/cache_test.go
- database/tbcd/level/headercache.go
- database/tbcd/level/level.go
- go.mod
- go.sum
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
**Summary**
We really should use size as the metric to determine cache size. This flips that for blockheaders.
**Changes**
This fixes a major bug in headers only mode where headers were not purged from the cache. This may have caused problems we had not diagnosed.
> tbcd: move block header cache from items to size

- database/bfgd/database.go
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
- database/bfgd/scripts/0013.sql
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
**Summary**
simpler finality calculations with new table
**Changes**
* add table who's rows each represent the lowest published btc block that an l2_keystone is found in
* on bfg startup, backfill existing l2_keystones' lowest btc block
* use pop_basis database notifications to continue to index these l2_keyston <-> lowest btc block
* update finality queries to use this
* add tests
more context:
this pr adds a database table `l2_keystones_lowest_btc_block`, which as `l2_keystone_abrev_hash` as a primary key.  this represents, for each distinct l2 keystone, the published lowest btc block this l2 keystone was found in. this way, we no longer have to calculate this at query time.
> bfgd: simpler finality calculations with new table

- .github/workflows/localnet-test.yml
- e2e/docker-compose.yml
- e2e/entrypointl2.sh
- e2e/optimism-stack.Dockerfile
- e2e/setup-raft.bash
**Summary**
op-conductor robustness fixes in localnet
**Changes**
some localnet fixes around robustness
modified "setup-raft.bash" script to allow configuration of op-conductor raft setup from environment
> op-conductor fixes + bootstrap script

- database/bfgd/postgres/postgres.go
- database/bfgd/scripts/0015.sql
- database/bfgd/scripts/0016.sql
- service/bfg/bfg.go
**Summary**
Found two bugs: 
if we stop iterating through txs due to a parse error, we can't finish the block.  don't stop parsing a block for an error like this
```
could not parse signature script: not a signature , found: 0x46
```
need to change `ON DELETE` to `ON UPDATE` and delete invalid `pop_basis`
**Changes**
* do not stop parsing a btc block if encountering a parse error, we may have a parse error partially down the block but we shouldn't halt parsing the rest of the txs for that
* sql update; delete invalid pop basis upon re-org
> better error handling + sql update

- cmd/hemictl/hemictl.go
- cmd/tbcd/tbcd.go
- database/tbcd/level/blockcache.go
- database/tbcd/level/cache_test.go
- database/tbcd/level/level.go
- database/tbcd/level/level_test.go
- service/tbc/tbc.go
**Summary**
Cache settings were not properly sent down the stack.
**Changes**
Don't use fixed defaults for cache sizes.
> tbcd: fix cache settings

- database/tbcd/database.go
- database/tbcd/level/level.go
- service/tbc/peermanager.go
- service/tbc/tbc.go
- Fixed typos such as "reutrns" to "returns", "tansaction" to "transaction", and "receice" to "receive".
- Made minor adjustments to logging messages and variable names for better consistency.
> Fix typographical errors

- database/tbcd/level/level.go
- service/tbc/tbc.go
This is needed to support synthetic blockheader inserts in headers only mode.
> tbc: check block does not exist prior to inserting into blocksmissing db

- database/tbcd/database.go
- database/tbcd/level/level.go
- service/tbc/tbc.go
**Summary**
We need a way to count all utxos for a specified scripthash. Unfortunately this does mean iterating through all utxos since leveldb does not have the upper limit as a call.
> tbc: add UtxosByScriptHashCount

- cmd/hemictl/README.md
- Add missing environment variables documentation
- Improve code examples and formatting
- Add error handling section
- Reorganize content with clear sections
- Add usage notes and best practices
- Remove sensitive information
> hemictl: improve readme docs

- config/config.go
- database/bfgd/scripts/0004.sql
- hemi/hemi.go
- service/bss/bss.go
- service/tbc/tbcfork_test.go
1. **`config.go`**:
- Corrected "unsuported" to "unsupported" in an error message.
2. **`0004.sql`**:
- Fixed "Contruct" to "Construct" in a comment.
3. **`hemi.go`**:
- Updated "unsuported" to "unsupported" in an error message.
4. **`bss.go`**:
- Corrected "succesful" to "successful" in a help description.
5. **`tbcfork_test.go`**:
- Fixed "unsuported" to "unsupported" in an error message.
> all: fix various spelling errors

- .github/workflows/localnet-test.yml
- README.md
- e2e/docker-compose.yml
- e2e/entrypointl2.sh
- e2e/optimism-stack.Dockerfile
**Summary**
This PR adds the commits that are running on testnet as we test hvmphase0.  It adds needed configuration for running op-geth with configured hvm
**Changes**
* add hvm phase 0 testing commits to localnet
* add hvm phase 0 starting timestamp to docker compose up
* make dependencies in docker compose more robust
> Localnet Update

- api/tbcapi/tbcapi.go
- cmd/tbcd/tbcd.go
- database/level/level.go
- database/tbcd/database.go
- database/tbcd/level/encodedecode_test.go
- database/tbcd/level/level.go
- database/tbcd/level/level_test.go
- e2e/e2e_ext_test.go
- hemi/hemi.go
- hemi/pop/pop.go
- service/bfg/bfg.go
- service/tbc/crawler.go
- service/tbc/crawler_test.go
- service/tbc/rpc.go
- service/tbc/rpc_test.go
- service/tbc/tbc.go
- service/tbc/tbcfork_test.go
**Summary**
Hemi needs to keep track of L2 keystones in order to provide callers the bitcoin view of the hemi network.
**Changes**
This PR adds L2 keystone indexing and hides this behind a configuration flag.
> tbcd, bfgd: add various hemi specific indexes

- service/tbc/tbc.go
**Summary**
Turns out leveldb closed can happen before context closure thus we must catch it like a pokemans.
> tbc: catch leveldb closed

- database/bfgd/postgres/postgres.go
- database/bfgd/scripts/0017.sql
**Summary**
since removing the "canonical chain" logic from bfg, we now handle what this index was doing within a db trigger (transaction) called clean_pop_basis.  leaving this index (the contraint) in would cause issues where ON UPDATE SET NULL may set more than one instance of the same pop basis to "unpublished", where it should in turn be deleted by the clean_pop_basis trigger.  but the index is throwing an error and not allowing that trigger to be hit
removing the index allows for the following to happen all in one transaction: any pop_bases that were re-orged off of the chain, set btc_block_hash to null (via ON UPDATE SET NULL) then delete them via clean_pop_basis.
**Changes**
remove index
> remove un-used index

- service/bfg/bfg.go
**Summary**
Reduce the level of the `handleBtcFinalityNotification write: <ip> <err>` log to `trace`.
**Changes**
> bfgd: reduce finality notification log to trace

- service/tbc/crawler.go
- service/tbc/tbc.go
**Summary**
I forgot to add a check for keystone indexer when calculating synced.
**Changes**
Add logic to determine if chain is synced when keystone indexers are enabled.
> tbc: add keystone indexer to synced calculation

- service/tbc/rpc.go
Not sure how this snuck into main.
**Summary**
Typo that broke the tree. Sorry about that.
**Changes**
> tbc: fix typo

- e2e/optimism-stack.Dockerfile
**Summary**
see title
**Changes**
see title
> localnet: upgrade op stack to latest hemi commits

- .github/workflows/localnet-test.yml
- e2e/deploy-config.json
- e2e/e2e_ext_test.go
**Summary**
a few fragile test fixes
**Changes**
as of now, op-conductor is not hvm-aware so we do not use it in higher environments.  there is a problematic step in localnet testing that is meant to test some op-conductor functionality.  this slows down the tests, is incorrect, and is inconsistent.  remove until we update op-conductor, at which time we will add an appropriate sequencer failover test
decrease l2 block time to speed up testing
a test that tests two bfgs doesn't wait for the insertion of l2 keystones, add that wait and add t.Parallel() so it doesn't block other parallel tests.
> fragile test fixes

- database/bfgd/postgres/postgres.go
- e2e/e2e_ext_test.go
**Summary**
there is a bug in the postgres query that only takes into account the first 100 bitcoin blocks when determining effective height, so if a keystone was published older than the first 100 it wouldn't get counted in effective height.
remove this clause; I am not sure why it was introduced but it is likely fallout from when trying to optimize these queries
add a test that should have caught this
**Changes**
see summary
> bfg: take into account l2 keystones that are more final than 100

- database/bfgd/database_ext_test.go
- database/database.go
- service/tbc/crawler.go
- Fixed wording in `database_ext_test.go`:  
- `"explicitely"` → `"explicitly"`  
- `"notfication"` → `"notification"`  
- Improved clarity in `database.go`:  
- `"doens't"` → `"doesn't"`  
- Adjusted comments in `crawler.go`:  
- `"aproximation"` → `"approximation"`  
- `"basicaly"` → `"basically"`  
- `"alreayd"` → `"already"`
> Fix spelling errors

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Updated Discord links in issue templates, replacing the old URL (`discord.gg/8z9antYtus`) with the new one (`discord.com/invite/hemixyz`).
- Updated the Discord link in **bug_report.yml**.
- Updated the Discord link in **config.yml**.
- Updated the Discord link in **feature_request.yml**.
These changes ensure that users are redirected to the correct and updated Discord server.
> Updated Discord links

- service/bfg/bfg.go
- service/bss/bss.go
- service/popm/popm.go
- service/tbc/crawler.go
- service/tbc/tbc.go
- service/tbc/tbcfork_test.go
Fixed grammatical and spelling errors in multiple service files.
service/bfg/bfg.go
Fixed typo in comment: "whe" → "when".
Corrected "canoncial" → "canonical".
service/bss/bss.go
Fixed typo "folloing" → "following".
Corrected "reconeect" → "reconnect".
service/popm/popm.go
Fixed typo "minbutes" → "minutes".
service/tbc/crawler.go
Fixed spelling errors: "aproximation" → "approximation", "basicaly" → "basically".
Fixed repeated typo "processedd" → "processed".
Fixed typo "anf" → "and".
service/tbc/tbc.go
Fixed typo "wil" → "will".
service/tbc/tbcfork_test.go
Fixed typo "suported" → "supported".
###Notes
These corrections improve code readability and clarity without affecting functionality.
> bfg, bss, popm, tbc: fix various typos

- cmd/btctool/blockstream/blockstream.go
- cmd/btctool/btctool.go
- cmd/hemictl/hemictl.go
- database/tbcd/level/level.go
**Summary**
Github detected various CodeQL vulnerabilites related to a few instances in the code where strings were getting parsed to int64 and uint64, which were later getting cast to int without checking the upper bounds.
**Changes**
Changed to parse these with 32 bits explicitly, so at the very least an error will return if the parsed string exceeds the int32 bounds, rather than a potential undetected overflow in 32-bit architectures.
> all: fix int64 and uint64 casting to int

- database/tbcd/database.go
- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/tbc.go
- service/tbc/tbcfork_test.go
**Summary**
fixupCache is massively parallel and it kills kooboornootees.
**Changes**
Make fixupCache serial.
> tbc: reduce threads used by fixup, misc improvements

- service/popm/popm_test.go
**Summary**
The test `TestConnectToBFGAndPerformMineALot` will at times fail with a race condition. After investigating, it _appears_ that since the BFG used in that test is a Mock BFG (which responds to requests much faster than a normal BFG), it will at times respond to a request before the pop miner is ready to receive it, after which the pop miner will get stuck in the mining process for that particular keystone until a timeout occurs. 
This does mean other tests using the Mock BFG might have also had this issue, but since it is rare, the one failing was usually this specific test, as it mines the most keystones.
The easiest way to fix this issue is to simply add a slight delay before each response. However, it may be worthwhile to investigate this problem further since it appears the …
> popm: fix fragile test

- service/bss/bss.go
- service/popm/popm_test.go
- service/tbc/peermanager.go
- service/tbc/tbc_test.go
- ttl/ttl_test.go
This PR corrects several spelling mistakes and improves consistency in variable names and comments across multiple files. It fixes issues such as typos in function parameters, expected output variables, and inline documentation, ensuring better readability and maintainability.
- Fixed the misspelling of `parrentCtx` to `parentCtx` across multiple functions in `service/bss/bss.go`.  
- Corrected `expectexTxOut` to `expectedTxOut` in `service/popm/popm_test.go`.  
- Fixed the function name typo `TestProcesAllKeystonesIfAble` to `TestProcessAllKeystonesIfAble` in `service/popm/popm_test.go`.  
- Corrected comment typo `caluse` to `clause` in `service/tbc/peermanager.go`.  
- Fixed `ecxpected` to `expected` in `service/tbc/tbc_test.go`.  
- Resolved `wamted` to `wanted` in `ttl/ttl_test.go`.
> all: fix various typos in variable names

- api/auth/auth.go
- e2e/e2e_ext_test.go
- service/popm/popm.go
"authenicate message too short" to "authenticate message too short".
"mulitiple" to "multiple".
"seperately" to "separately".
> api/auth, e2e, popm: fix minor spelling mistakes

- database/tbcd/level/blockcache.go
- database/tbcd/level/cache_test.go
- database/tbcd/level/level.go
**Summary**
Add a diagnostic to root cause a bug.
**Changes**
> tbc: use chainhash.Hash without pointers in the lowIQLRU cache

- cmd/bfgd/bfgd.go
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
**Summary**
Add a configuration option `BFG_DISABLE_PUBLIC_CONNS` to disable public WebSocket connections on BFG.
When a PoP Miner connects and this option is enabled, the PoP Miner will be disconnected with an authentication error, which will result in the PoP Miner not retrying the connection.
**Changes**
- Add `BFG_DISABLE_PUBLIC_CONNS` environment variable to BFG.
- Add handling to close public WebSocket connections with a `protocol.ErrPublicKeyAuth` error when `DisablePublicConns` is `true`.
> bfg: add config option to disable public ws conns

- api/tbcapi/tbcapi.go
- cmd/hemictl/hemictl.go
- database/tbcd/database.go
- database/tbcd/level/blockcache.go
- database/tbcd/level/cache_test.go
- database/tbcd/level/headercache.go
- database/tbcd/level/level.go
- database/tbcd/level/level_test.go
- service/tbc/crawler.go
- service/tbc/rpc.go
- service/tbc/rpc_test.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
**Summary**
Turns out some callers send in nil and play with the underlying data so we cannot reliably use pointers to hashes. Convert them to stack variables. There is no real impact on performance at the cost of some stack space but this does harden the call stack considerably.
**Changes**
> tbc: convert hash pointers to hashes as variable arguments

- cmd/tbcd/tbcd.go
- service/popm/popm.go
**Summary**
Change the default PoP Miner and tbcd networks to Bitcoin mainnet.
**Changes**
- Change PoP Miner default network to Bitcoin mainnet.
- Change TBC default network to Bitcoin mainnet.
> all: change default network to mainnet

- service/tbc/peer/rawpeer/rawpeer.go
- service/tbc/peer/rawpeer/rawpeer_test.go
- service/tbc/tbcfork_test.go
**Summary**
Fixes a [race condition ](https://github.com/hemilabs/heminetwork/actions/runs/13774032146/job/38519089244) that occurs due to multiple blockheader messages being sent to TBC before it has time to read them.
**Changes**
Fix slight error in locking mechanism for rawpeer conn writes, and added a test that should make it easier to identify hidden race conditions such as this one.
> tbc: fix race condition in fork tests

- localnode/NODE_RUNNING.md
- localnode/docker-compose.yml
- localnode/docker-compose_mainnet.yml
- localnode/heminode.sh
Handle testnet containers better in script
**Summary**
**Changes**
> Remove network from compose names

- database/tbcd/level/cache_test.go
**Summary**
printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)go-staticcheck
**Changes**
> database/tbcd/level: fix printf-style function used with no args

- service/popm/popm.go
- service/popm/popm_test.go
**Summary**
Fix #422 
**Changes**
Prior, whenever the channel that would receive bfg responses in pop miner was busy, we would no-op. this happened often because the channel was not buffered. this would happen silently as well. add a timeout to sending messages to the non-buffered channel and log and error if we time out
> popm: don't instantly noop if bfg response channel is busy

- database/bfgd/database.go
- database/bfgd/postgres/postgres.go
- service/bfg/bfg.go
**Summary**
when saving records from processing bitcoin blocks, prior they were not done atomically (in a db tx).  this means that if one failed others may succeed.  this change makes it all-or-nothing; we either save everything we want from a btc block or we don't, so we don't half-save.
**Changes**
see summary
> BFG: save db records in processBitcoinBlock in a single tx

- .github/workflows/go.yml
**Summary**
Split the Go workflow's "Build" job into 3 separate jobs. This allows make build, make test and make race to be run in parallel.
On average this speeds up CI by about 1 minute and 30 seconds, which I believe is a welcome change.
Ideally, requiring `Go / Build`, `Go / Lint` and `Go / Test` to pass prior to merging a pull request (in repository rule-sets) would prevent broken pull requests from being merged (@jcvernaleo).
**Changes**
> ci: split go build job to improve runtime

- .github/workflows/go.yml
- .github/workflows/node.yml
- .github/workflows/release.yml
- .golangci.yaml
- Makefile
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
- database/tbcd/level/cache_test.go
- database/tbcd/level/encodedecode_test.go
- database/tbcd/level/level_test.go
- e2e/e2e_ext_test.go
- service/popm/popm_test.go
- service/tbc/peer/rawpeer/rawpeer_test.go
- service/tbc/rpc_test.go
- service/tbc/tbc_test.go
- ttl/ttl_test.go
**Summary**
Switch from using go-header (via golangci-lint) to [golicenser](https://github.com/joshuasing/golicenser).
`golicenser` has the following advantages:
- Processes files in parallel (faster)
- Correctly handles auto-fixes (does not place regex in the updated headers)
- Uses Git to for copyright year ranges.
- Maintained by me, so quick bug fixes if necessary :)
**Changes**
- Remove use of `go-header` from golangci-lint config.
- Add golicenser to `make lint-deps`
- Add golicenser to `make lint`
- Add golicenser to "Go / Lint" job
- Use Go 1.24 for building in CI.
**Notes**
golicenser is not currently included in golangci-lint. Once it is, we can have it configured through the `.golangci.yml` file and the extra Make / GitHub Actions parts will no longer be necessary. Running as a …
> all: use golicenser instead of go-header

- localnode/NODE_RUNNING.md
- localnode/docker-compose.yml
- localnode/docker-compose_mainnet.yml
> docker: add profiles to compose files

- .github/workflows/localnet-test.yml
- docker/bfgd/Dockerfile
- docker/bssd/Dockerfile
- docker/popmd/Dockerfile
**Summary**
Use `make go-deps` instead of `make deps` to avoid installing linting/vulncheck dependencies when not necessary.
**Changes**
> docker, ci: use make go-deps to avoid installing lint deps

- .github/workflows/localnet-test.yml
- .golangci.yaml
- README.md
- cmd/tbcd/README.md
- docker/bfgd/Dockerfile
- docker/bfgd/goreleaser.Dockerfile
- docker/bssd/Dockerfile
- docker/bssd/goreleaser.Dockerfile
- docker/popmd/Dockerfile
- docker/popmd/goreleaser.Dockerfile
- e2e/monitor/README.md
- e2e/monitor/go.mod
- go.mod
- localnode/docker-compose.yml
- localnode/docker-compose_mainnet.yml
**Summary**
Update builds to use Go 1.24.1. This does not change the Go version for the `github.com/hemilabs/heminetwork` module, meaning this is not affect dependants.
**Changes**
- Update Go toolchain to `go1.24.1`
- Update remaining Go versions in GitHub Actions to `1.24.x`
- Update documentation to say "Go 1.24" instead of "Go 1.23"
- Update golang base images to `golang:1.24.1-alpine3.21`
- Update alpine images to `alpine:3.21.3`
> all: build with go1.24.1

- .github/workflows/go.yml
- .golangci.yaml
- Makefile
- database/database.go
- service/bfg/bfg.go
- service/tbc/tbc.go
**Summary**
Update golangci-lint to v2. This changes the configuration schema, introduces some new rules, and removes deprecated linters. Additionally, the linter `gosimple` has been merged into `staticcheck`.
**Changes**
- Update `golangci-lint` to `v2.0` in `make lint-deps`
- Update `golangci/golangci-lint-action` to `v7.0.0` in CI.
- Update `golangci-lint` to `v2.0` in CI
- Update `golangci.yml` configuration file to new schema
- Disable `QF1001: could apply De Morgan's law` staticcheck rule, as it formats Marco's code and makes it somewhat harder to read.
- Fix new linting issues.
> all: update golangci-lint to v2

- localnode/NODE_RUNNING.md
> dokcer: update requirements

- localnode/docker-compose_mainnet.yml
**Summary**
bssd can TECHNICALLY run without bfgd, so don't declare it as a dependency.  this makes it easier to run HEMI-only nodes
**Changes**
see summary
> localnode: remove bfgd as a dependency of bssd

- localnode/NODE_RUNNING.md
> localnode: update node running docs

- service/tbc/tbcfork_test.go
**Summary**
Inside our fork tests, we send blocks to TBC and then check the db for tests. However, TBC might take longer than expected to insert the blocks, so we must wait for the blocks to be inserted before checking the db.
**Changes**
Explicitly check that all blocks were inserted before proceeding with tests.
> tbc: fix fork tests failing if tbc is slow to insert blocks

- .github/workflows/go.yml
- .golangci.yaml
- Makefile
- cmd/keygen/keygen.go
- service/bfg/bfg.go
- service/tbc/crawler.go
- service/tbc/tbc.go
**Summary**
Update golangci-lint to `v2.1` and golicenser to `v0.3`.
**Changes**
- Update `golangci-lint` from `v2.0` to `v2.1`
- Update `golicenser` from `v0.1` to `v0.3`
- Enable `makezero` linter: Detects slice declarations with non-zero length which are later used in `append` (detects bugs).
- Enable `noctx` linter: Detects HTTP requests without `context.Context`.
- Enable `usestdlibvars` linter: Detects variables that could be replaced with a variable/constant from stdlib.
- Enable `usetesting` linter: Detects use of functions that have a `testing` package alternative in tests (e.g. `os.CreateTemp`, `os.TempDir`, etc.)
- Enable `whitespace` linter: Detects unnecessary newlines at the start and end of functions, if, for, etc.
**Notes**
Hopefully golicenser will be included in a …
> all: update golangci-lint, golicenser

- database/tbcd/level/upgrade.go
- rawdb/rawdb.go
**Summary**
Saw a panic on rad database close close for using `r.index` after it was reset to nil. Use a bool to indicate if a db is open instead of relying on r.index thus removing the possibility of a race.
**Changes**
> tbc: avoid race with r.index on Close

- .golangci.yaml
- api/auth/secp256k1_test.go
- api/protocol/protocol.go
- config/config_test.go
- database/bfgd/database_ext_test.go
- database/tbcd/level/cache_test.go
- database/tbcd/level/level_test.go
- e2e/e2e_ext_test.go
- hemi/electrs/conn_pool.go
- rawdb/rawdb_test.go
- service/bfg/bfg_test.go
- service/popm/popm_test.go
- service/tbc/peer/peer_test.go
- service/tbc/peer/rawpeer/rawpeer_test.go
- service/tbc/rpc_test.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
**Summary**
Previously, we were not linting any test files. This enables linting test sources, and fixes all linting issues currently reported for the tests.
**Changes**
- Enable golangci-lint linting test sources
- Ignore `websocket.Close` for the `bodyclose` linter, as closing the response body is handled by the websocket library.
- Fix issues reported by golangci-lint for tests (mostly duplicated packages, unused code, etc.)
There were a few ineffective assignments, two of which I was unable to determine why they were there - they both have `nolint` comments. Please let me know if you think they should be removed or kept.
I have commented out unused functions, however I think removing them would be best if we do not plan on using them in the near future - @marcopeereboom?
> all: enable linting test sources

- service/bfg/bfg.go
- service/bss/bss.go
- service/deucalion/deucalion.go
- service/popm/prometheus.go
- service/tbc/crawler.go
- service/tbc/tbc.go
**Summary**
All our cloud infrastructure apparently needs an additional health route instead of calling RPCs.
**Changes**
Add a `/health` route to the same mux as the prometheus server for cloud infra.
> deucalion: add health route

- localnode/gen-files.sh
**Summary**
prior, the way we were escaping quotes was preventing the entrypoint.sh file to recognize an existing datadir, fix those
**Changes**
see summary
> fix escaping quotes that were re-recreating geth datadir

- localnode/NODE_RUNNING.md
simple fix: "Etherem" → "Ethereum"
**Changes**
"Etherem" → "Ethereum"
> fix typo Update NODE_RUNNING.md

- api/protocol/protocol.go
fix typo in protocol.go
before: 
- "parasable"
after:
- "parsable"
> api/protocol: fix typo

- database/tbcd/level/upgrade.go
- go.mod
- go.sum
**Summary**
there is a build error when GOOS=openbsd GOARCH=amd64 and building tbc; the v3 of the gopsutil will not build. however it will build with v4. 
fixes #511
**Changes**
remove usese of v3 and just use v4.
> remove use of github.com/shirou/gopsutil@v3 in tbc

- e2e/monitor/go.mod
- e2e/monitor/go.sum
- go.mod
- go.sum
**Summary**
with go toolchains 1.24.3 or 1.23.9, github.com/ebitengine/purego v0.8.2 will fail to build with the following error:
```
link: duplicated definition of symbol dlopen, from github.com/ebitengine/purego and github.com/ebitengine/purego
```
fixes #513
**Changes**
this can be avoided by upgrading the dependency to v0.8.3.  do so.
> upgrade dependency github.com/ebitengine/purego to avoid regression

- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
**Summary**
when calculating effectiveHeight, we're not taking into account the ignore (we only do so when querying for blocks), add that to the effectiveHeight calculation
add test case for this
**Changes**
make sure that the invalid keystones are taken into account with effectiveHeight
> do not include invalid keystones in effectiveHeight

- .goreleaser.yaml
- docker/tbcd/Dockerfile
- docker/tbcd/goreleaser.Dockerfile
**Summary**
Add Docker image for `tbcd`, and setup GoReleaser to build and publish the image.
**Changes**
- Add scratch Docker image for `tbcd`.
- Add GoReleaser-specific scratch Docker image for `tbcd`.
- Remove building `tbcd` for armv7 in releases.
- Setup GoReleaser to build and publish `hemilabs/tbcd` image for amd64 and arm64.
- Setup GoReleaser to publish Docker multi-arch manifests for `hemilabs/tbcd`.
> docker: add tbcd image

- .golangci.yaml
- api/auth/secp256k1_test.go
- database/bfgd/database_ext_test.go
- database/tbcd/level/level_test.go
- docker/bfgd/Dockerfile
- docker/bssd/Dockerfile
- docker/popmd/Dockerfile
- e2e/e2e_ext_test.go
- e2e/monitor/go.mod
- e2e/monitor/main_test.go
- e2e/optimism-stack-legacy.Dockerfile
- e2e/optimism-stack.Dockerfile
- go.mod
- hemi/electrs/conn_pool_test.go
- hemi/electrs/conn_test.go
- service/popm/popm_test.go
- service/tbc/crawler_test.go
- service/tbc/peer/peer_test.go
- service/tbc/peer/rawpeer/rawpeer_test.go
- service/tbc/peermanager_test.go
- service/tbc/rpc_test.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
- ttl/ttl_test.go
**Summary**
Update Go version to `1.24` (and toolchain `go1.24.4`).
**Changes**
- Update required go version in `go.mod` to `1.24`.
- Update go toolchain version in `go.mod` to `1.24.4`.
- Update golang Docker images to `1.24.4-alpine3.22` and `1.24.4-bookworm`.
- Update tests to use `(*testing.T).Context()` instead of `context.Background()` or `context.TODO()`.
> all: update go to 1.24 (toolchain 1.24.4)

- e2e/optimism-stack-legacy.Dockerfile
**Summary**
as of now, the way we build localnet is that we "snapshot" network
creation at certain versions, if we want to update those versions we
need to ensure all dependencies work together.  as of now, they do not.
revert the changes that caused this.
**Changes**
see summary
> e2e: revert legacy dockerfile

- Makefile
The linter and real world should be kept in sync. This is destroying my workflow.
---
Install `gofumpt` in the `lint-deps` Make target so that the version of gofumpt on Marco's machine does not get out of sync with the version used by golangci-lint. Slowdown in CI is thankfully minimal because we use golangci-lint directly instead of via Make.
> make: install gofumpt in lint-deps

- service/tbc/tbcfork_test.go
**Description:**  
This pull request corrects minor typos in comments within the test file:
- Replaces "dowloads" with "downloads"
- Replaces "postive" with "positive"
> tbc: fix miscellaneous typos

- database/tbcd/level/upgrade.go
**Summary**
When merging the [db v4 PR](https://github.com/hemilabs/heminetwork/pull/539), I thought the commenting out of the warning given to the user prior to a v3 upgrade was done on purpose. It wasn't 🙂
**Changes**
Uncommented the warning.
> level: re-enable db v3 upgrade warning

- cmd/keygen/keygen.go
This PR makes the following changes and improvements to the keygen command-line tool:
Removed duplicate flag.Parse() call in main()
Calling flag.Parse() more than once can cause a panic in newer Go versions (see flag.Parse() docs). The redundant second call was removed to prevent unexpected behavior.
> cmd/keygen: remove duplicate flag.Parse call

- Makefile
- cmd/hemictl/hemictl.go
- cmd/hproxyd/hproxyd.go
- service/hproxy/ethereum.go
- service/hproxy/hproxy.go
- service/hproxy/hproxy_test.go
**Summary**
proxyd tried to solve all problems and per the laws of physics, it made everything worse.
hproxy is a dead simple replacement that throws opgeth commands over the fence and maintains a list of concurrent nodes.
**Changes**
No changes, all greenfield.
> hproxy: a much simpler proxyd replacement

- docker/hproxy/Dockerfile
- docker/hproxy/goreleaser.Dockerfile
**Summary**
This PR aims to create the necessary files to run an hproxyd docker container.
In order to test, from inside the repo's root directory, run:
```
$ docker build -t hproxy:latest -f ./docker/hproxy/Dockerfile .
$ docker run hproxy:latest
```
**Changes**
Created the necessary files.
> docker: add hproxy docker files

- service/tbc/peer/peer_test.go
**Summary**
fix unused variable caught by linter
**Changes**
see summary
> tbc: fix unused variable

- .github/workflows/release.yml
**Summary**
Restrict token permissions for `test-go` job in release workflow. These token permissions are limited inside the `go.yml` workflow itself, however GitHub flagged this as a risk and it does not hurt to restrict them here as well.
Fixes https://github.com/hemilabs/heminetwork/security/code-scanning/16
**Changes**
- Add `permissions` block to `test-go` job in `release workflow`, limiting the `GITHUB_TOKEN` permissions to reading contents only.
> ci: restrict token permissions in release workflow

- e2e/e2e_ext_test.go
- service/bfg/bfg_test.go
- service/popm/popm.go
- service/popm/popm_test.go
- testutil/mock/mock.go
**Summary**
Fixes a few more tests.
**Changes**
For some reason, some important settings were not being set in `popm`, which broke the tests (correctly). This has been fixed. 
Also changed the `close` behavior on the websocket connections of the mock servers.
> popm, bfg: more test fixes

- bitcoin/wallet/wallet.go
- bitcoin/wallet/wallet_test.go
- cmd/popmd/popmd.go
- config/config.go
- service/popm/popm.go
- service/popm/popm_test.go
**Summary**
Currently, fee calculation for pop miners is done by the gozer. However, the only functional gozer is TBC, which requires the mempool to be enabled in order for fee estimation to work. This can be both expensive and potentially unreliable. As such, an option to override fee estimation with a static fee was added.
**Changes**
Introduce a way to set a static fee for the pop miner.
Changed the wallet transaction creation methods to allow float sats/byte fees.
Changed config.go to be able to parse float values in env vars.
> popm: add static fee override

- e2e/monitor/bindings/README.md
> e2e/monitor: fix typo in bindings readme

- bitcoin/wallet/gozer/tbcgozer/tbcgozer_test.go
- testutil/mock/geth.go
**Summary**
The `TestTbcGozer` test seems to timeout at times. This is likely due to using a real TBC instance and making various calls to it. Even if this does not fix the error, I believe it is still good to separate the functionality and connection logic of the test into two.
Also changes how the `mock opgeth` server handles reading messages.
**Changes**
Separate this test into two:
- `TestTBCGozerConnection`: connect to a real TBC instance and make an inexpensive call.
- `TestTBCGozerCalls`: connect to a mock TBC instance and make various calls.
Use `Reader` rather than `Read` to receive messages in the mock opgeth server, as the latter will return EOF if there is no message to be read.
> tbcgozer, mock: reader logic & add additional test

- .github/workflows/release.yml
- .goreleaser.yaml
**Summary**
Update release workflow to create supply chain attestations for release assets and Docker images.
Supply chain attestations provide verifiable, cryptographically signed statements that provide evidence of an artifact's origin, security posture, and build process.
**Changes**
- Use `actions/attest-build-provenance` for release artifacts in the `release.yml` workflow.
- Update GoReleaser config to create SBOMs and provenance when building Docker images.
- Remove unused environment variables from `release.yml` workflow.
- Fix GoReleaser deprecation warnings (`archives.format` -> `archives.formats`, `archives.format_overrides.format` -> `archives.format_overrides.formats`)
> ci, goreleaser: add supply chain attestations

- .goreleaser.yaml
**Summary**
Disable Docker attestations in GoReleaser. With the current setup, this results in indexes being created for each architecture image, which cannot be used to then create a Docker cross-platform manifest, which will cause build failure.
In the future, we can consider switching to using https://ko.build/ with GoReleaser to build Docker images, which properly supports these features and builds much nicer cross-platform images.
**Changes**
- Remove `--sbom=true` and `--provenance=mode=max` flags from Docker builds in GoReleaser.
> goreleaser: temporarily remove docker attestations

- service/tbc/rpc_test.go
**Summary**
Fixes #639 
**Changes**
Change test to compare received and expected errors, rather than received and expected responses, as the latter required the use of `deep` and was prone to fragility and one byte differences.
> rpc: fix TestNotFoundError

- .github/workflows/go.yml
- api/auth/secp256k1.go
- bitcoin/wallet/gozer/tbcgozer/tbcgozer.go
- bitcoin/wallet/gozer/tbcgozer/tbcgozer_test.go
- cmd/btctool/btctool/btctool.go
- database/tbcd/database_test.go
- hemi/electrs/electrs.go
- hemi/pop/pop_test.go
- version/useragent.go
**Summary**
Fixes #637
Additionally, fixes a fragility found in `TestTBCGozerCalls` found while making this PR, and probably all other tests dependent on `tbcGozer`
To ensure that this was indeed the error, the go.yml file was temporarily changed to run `go test`and `go test -race` with `count=20` and was run multiple times. 
**Changes**
Remove `default` from sending the result of `handleTBCWebsocketCall` back to the caller, as that would sometimes race and the caller would not be listening for the channel. Instead, sending the result will be tied to a context with timeout that matches the timeout on the caller side, ensuring neither side becomes stuck.
> tbcgozer: fix fragile tests

- service/tbc/mempool.go
- service/tbc/tbc.go
Somehow I picked a genesis point that was forked out. Replace with the correct hash. While fix a debug message that should not be printed at every block insertion.
> tbc: Fix hemi keystone genesis.

- api/tbcapi/README.md
Replace relative path reference to SECURITY.md with correct GitHub URL
- Fix broken link from ../../SECURITY.md to https://github.com/hemilabs/.github/blob/main/SECURITY.md
- Aligns with the security policy link used in the main README.md
- Resolves file not found error when accessing the security policy documentation
> tbcapi: update broken SECURITY.md link in readme

- CHANGELOG.md
- CONTRIBUTING.md
**Summary**
Add `CONTRIBUTING.md` file that contains:
- Overall introduction to contributing to this repository
- Development environment setup (with `make` command examples)
- Code style guide
- Commit message style guide
- Pull requests guide
- Changelog guide
- Maintainer's guide
- Versioning
- Release cycle
- Release preperation
- Creating releases
This overrides the `CONTRIBUTING.md` file from the `.github` repository, as its contents are primarily JavaScript-focused and not relevant in this repository.
Closes #583, #627.
Related to: #644
**Changes**
- Add `CONTRIBUTING.md` file.
- Add initial stub `CHANGELOG.md` file (contents will be added in separate PR).
> all: add contributing guide

- CHANGELOG.md
**Summary**
Update the changelog file to document changes in v2.0.0.
**Changes**
- Update changelog for v2.0.0:
- Document breaking changes, additions, changes, fixes and removals.
- Based off of changes shown in https://github.com/hemilabs/heminetwork/compare/v1.6.3...HEAD as well as commits in all merged pull requests.
- Excludes changes to tests or dependencies.
It is likely this has missed a few items. Please read through the changelog and let me know if anything seems missing.
The contributors list is generated using:
```sh
previous_tag=$(gh release view --repo hemilabs/heminetwork --json tagName | jq -r '.tagName // empty')
contributors=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
"/repos/hemilabs/heminetwork/compare/$previous_tag...HEAD" …
```
> changelog: add initial changelog for v2.0.0

- docker/bfgd/Dockerfile
- docker/bfgd/goreleaser.Dockerfile
- docker/hproxyd/Dockerfile
- docker/hproxyd/goreleaser.Dockerfile
- docker/popmd/Dockerfile
- docker/popmd/goreleaser.Dockerfile
- docker/tbcd/Dockerfile
- docker/tbcd/goreleaser.Dockerfile
- e2e/optimism-stack.Dockerfile
- go.mod
**Summary**
Update Go to 1.24.7 before v2 release.
The latest version of Go is 1.25, which we should update to after the `v2.0.0` tag has been made.
**Changes**
- Update Go toolchain to `go1.24.7`
- Update golang alpine image to `golang:1.24.7-alpine3.22`
- Update golang debian image to `golang:golang:1.24.7-bookworm`
- Update alpine image to `3.22.1`
> all: update to go 1.24.7

- service/popm/popm.go
- service/popm/popm_test.go
- testutil/mock/mock.go
**Summary**
Fixes #664 
**Changes**
As previously discussed, replaces the exponential backoff with a fully random backoff.
On disconnect, attempt to reconnect after [minDelay, MaxDelay].
> service/popm: add fully random backoff

- .github/workflows/labeler.yml
**Summary**
Prevent `gh api` commands from failing the labeler workflow. The `gh api` commands will fail when a label is already applied (add) or has not been applied (remove).
**Changes**
- Add `2>&1 || true` to ignore stderr output and always exit with `0`
> ci: fix gh api errors failing labeler job
