hemilabs/heminetwork

- api/tbcapi/tbcapi.go
- service/tbc/rpc.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
**Summary**
added tbcapi-utxos-by-address
**Changes**
* getting utxos by address
* allowing pagination
* added tests
fixes #44
>  added tbcapi-utxos-by-address endpoint

- api/tbcapi/tbcapi.go
- database/tbcd/level/level.go
- service/tbc/rpc.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
**Summary**
added tx-by-id endpoint
**Changes**
* added endpoint to get tx by id
* updated db query to use BytesPrefix
fixes #48
> added tx-by-id endpoint

- .gitignore
**Summary**
Add common user-specific files to the `.gitignore` file.
**Changes**
- Add common Vim temporary files to `.gitignore`
- Add common JetBrains temporary/user-specific files to `.gitignore`
- Add common Visual Studio Codes temporary/user-specific files to `.gitignore`
> Add common user-specific files to gitignore

- service/tbc/rpc.go
- service/tbc/tbc.go
**Summary**
Refactor TBC RPC handling to be more consistent with BFG/BSS
Additionally, this allows us to properly log internal errors, and makes adding and maintaining request handlers easier.
**Changes**
- Refactor TBC RPC handling to match BFG/BSS
> tbc: improve rpc request handling

- service/tbc/tbc.go
- ttl/ttl.go
- ttl/ttl_test.go
> Kill all pending block downloads if a peer fails

- web/popminer/popminer.go
- web/www/index.html
- web/www/index.js
Added a configuration field for setting a static fee, so web PoP miner has configuration parity with current downloadable PoP miner daemon.
> Add configuration option for static fees to web PoP miner

- service/bfg/bfg.go
**Summary**
Fix issues reported by staticcheck for code related to bfg
**Changes**
- Fix `github.com/btcsuite/btcd/wire` being imported more than once (ST1019)
- Simplify error comparison (S1002)
- Remove unused fields and variables
> bfg: fix issues reported by staticcheck

- database/tbcd/database.go
**Summary**
**Changes**
Not sure what happened but these functions fell off during the last commit.
> Fix missing panic

- service/popm/popm.go
**Summary**
Randomly select an available UTXO after filtering the available UTXOs that have a value equal to or greater than the required value for the transaction.
Previously, the selection was not random, and the first UTXO with a value equal to or greater than the required value would be used.
**Changes**
- Rewrite `pickUTXOs` function to return a randomly selected UTXO after filtering the available UTXOs that have a value greater than or equal to the required value needed for the transaction.
- Rename `pickUTXOs` to `pickUTXO` and return `*bfgapi.BitcoinUTXO` instead of `[]*bfgapi.BitcoinUTXO`, as only one UTXO is ever returned
- Add more debug logs for debugging UTXO-related issues
> popm: improve UTXO selection when creating Bitcoin transaction

- e2e/e2e_ext_test.go
- service/bfg/bfg.go
**Summary**
removing insertion of pop_basis from req/res flow as to not block response.  giving two retries each with 5 second to insert.
**Changes**
remove `pop_basis` from request/response cycle
> inserting unconfirmed pop_basis async

- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/tbc.go
**Summary**
We are seeing an impossible condition on prod. This branch adds additional debugability when that happens.
**Changes**
> Fix p2p network stalls.

- e2e/e2e_ext_test.go
- service/popm/popm_test.go
instead of ignoring the wrong commands, wait until the correct one until the test times out
**Summary**
**Changes**
> more fragile test fixes

- service/bfg/bfg.go
**Summary**
debugging with @joshuasing , we were noticing in `pprof` output that we have many goroutines hanging at the request limiter, we then realized that we don't stop waiting if the request's context is done.  therefore we (very likely) have a bunch of goroutines with "done" contexts that are hanging and hogging resources
**Changes**
when using the request limiter, ensure that we don't continue to wait on a context that is done
> check for ctx.Done() when using request limiter

- cmd/tbcd/tbcd.go
- database/tbcd/database.go
- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/mempool.go
- service/tbc/peer.go
- service/tbc/peer_manager.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
**Summary**
**Changes**
This adds a mempool struct that adds/removes tx's from the mempool. Also add some pretty stats to print during block download.
> Add mempool handling to tbc

- cmd/hemictl/hemictl.go
- database/tbcd/database.go
- database/tbcd/level/level.go
- service/tbc/crawler.go
- service/tbc/tbc.go
> Only return a single block where a tx was mined as found by yhe utxo indexer

- e2e/genesisl2.sh
**Summary**
run forge script in non-interactive mode in shell script
**Changes**
add `--non-interactive` flag to the `forge script` command
> run forge script in non-interactive mode in shell script

- service/tbc/tbc.go
> Remove DB call from tbc Server

- database/tbcd/level/level.go
**Summary**
This is a pretty bad bug that was introduced by yours truly when adding the feature to deal with a blockheader message that overlapped previous blockheaders.
**Changes**
This fixes the bug by reading wbh (wire block header) later instead of always using the zeroth element.
> tbc: fix regression where we were linking the wrong blockheaders

- e2e/monitor/go.mod
**Summary**
update go version in localnet test go.mod file
**Changes**
update go version in localnet test go.mod file
> update go version in localnet test go.mod file

- api/bfgapi/bfgapi.go
- api/bssapi/bssapi.go
- database/bfgd/database.go
- database/bfgd/database_ext_test.go
- database/bfgd/postgres/postgres.go
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
- service/bss/bss.go
**Summary**
added page and limit to finalities by keystones request, defaulting limit to 100 if 0 and setting an upper limit of 100 per page
**Changes**
added page and limit to finalities by keystones request, defaulting limit to 100 if 0 and setting an upper limit of 100 per page
> added page and limit to finalities by keystones request

- service/tbc/peer.go
- service/tbc/tbc.go
> Fix major part of stalls and an index loop bug.

- localnode/docker-compose_mainnet.yml
> fixed static peer id for op-node

- .github/workflows/go.yml
- .golangci.yaml
- Makefile
- api/auth/secp256k1.go
- cmd/btctool/btctool.go
- cmd/btctool/btctool/btctool.go
- cmd/hemictl/hemictl.go
- database/bfgd/postgres/postgres.go
- database/level/level.go
- database/postgres/postgres.go
- hemi/hemi.go
- hemi/pop/pop.go
- license_header.txt
- service/bfg/bfg.go
- service/bss/bss.go
- service/tbc/crawler.go
- service/tbc/crawler_test.go
- service/tbc/peermanager.go
- service/tbc/tbc.go
- ttl/ttl.go
**Summary**
Switch to [`golangci-lint`](https://golangci-lint.run/) for linting.
`golangci-lint` runs linters in parallel, supports caching and deduplicated errors. It is overall easier to work with, and a lot quicker than our previous solution (and can be customised more, and supports even more linters!)
Run `make lint-deps` to install `golangci-lint` on your machine if `make lint` fails.
Currently, only the following linters are enabled:
- errcheck - Checks for unchecked errors.
- gci - Enforces package import order, making it deterministic (similar to `goimports`).
- gofumpt - Runs gofumpt.
- goheader - Enforces copyright header.
- gosimple - Checks for ways to simplify code.
- gomoddirectives - Manages 'replace', 'retract' and 'excludes' directives in go.mod.
- govet - Runs go vet.
- …
> all: use golangci-lint for linting

- database/tbcd/database.go
- database/tbcd/database_test.go
- database/tbcd/level/level.go
- database/tbcd/level/level_test.go
> Add batched medata put/get and wrap them in transactions

- api/tbcapi/tbcapi.go
- cmd/hemictl/hemictl.go
- service/tbc/rpc.go
- service/tbc/tbc.go
> tbcapi, tbcd: expose async block download, add BlockInsert

- version/version.go
**Summary**
Prepare to release v0.7.0.
**Changes**
- Update version constants to represent v0.7.0.
> version: bump to 0.7.0

- version/version.go
**Summary**
Prepare to release version 1.0.0.
**Changes**
- Update version constants to represent v1.0.0.
> version: bump to 1.0.0

- rawdb/rawdb.go
- service/tbc/peer/rawpeer/rawpeer.go
- service/tbc/tbcfork_test.go
**Summary**
* fix fragile test; handle for error type that wasn't previously being handled for
* fix race condition; ensure that Close gets the mutex so it doesn't clash with Write
**Changes**
(see summary)
>  fragile test case + race condition fixes

- service/deucalion/deucalion.go
- service/tbc/mempool.go
- service/tbc/tbc.go
**Summary**
Fix hacker one findings.
**Changes**
> Fixup hackerone findings

- hemi/electrs/electrs.go
- service/bfg/bfg.go
- service/tbc/tbc.go
**Summary**
Rework prometheus a bit to mimic tbc.
**Changes**
> Add prometheus namespace

- README.md
fixed the link in the documentation, please review
**Changes**
> readme: fix bfgd link

- api/tbcapi/README.md
1) Add data type formats and examples
2) Improve type descriptions and explanations
3) Add links to contribution and security docs
4) Fix emoji consistency in TOC
5) Add detailed JSON examples
6) Improve table formatting and readability
> api/tbcapi: improve protocol documentation

- hemi/hemi.go
Fix spelling errors
**Summary**
Fix spelling errors
**Changes**
fix:  misspellings "unsupported"
> hemi: fix typo "unsupported" in error

- service/bfg/bfg.go
- service/bss/bss.go
> bfgd: adjust level of noisy logs

- service/bfg/bfg.go
**Summary**
Quieter log line.
**Changes**
See summary.
> bfg: quieter log

- api/auth/auth.go
- e2e/e2e_ext_test.go
- service/bfg/bfg.go
This pull request contains changes to improve clarity, correctness and structure.
> all: fix various typos

- e2e/optimism-stack.Dockerfile
**Summary**
update op-geth and optimism commits in localnet 
**Changes**
see summary
> Localnet fix

- localnode/docker-compose_mainnet.yml
> localnode: fix some compose formatting

- database/tbcd/level/level_test.go
> fix: duplicated import chainhash

- localnode/entrypointl2.sh
- localnode/mainnet-entrypointl2.sh
Make mainnet and testnet entrypoint files more consistant
**Summary**
**Changes**
> fix some options in compose

- .github/workflows/yml.yml
- e2e/docker-compose.yml
- localnode/docker-compose.yml
- localnode/docker-compose_mainnet.yml
**Summary**
- Fixed `e2e` and `localnode` docker compose yaml files
- Added a yaml linter gh action for those specifc files
> ci: fixed yml files and added gh action

- localnode/gen-files.sh
> Fix incorrection option

- localnode/docker-compose.yml
**Summary**
update localnode image to be our pectra commit
**Changes**
see summary
> update op-node image to be pectra

- localnode/gen-files.sh
- localnode/rollup.json
> Update testnet rollup.json

- localnode/docker-compose.yml
- localnode/docker-compose_mainnet.yml
This is useful for testing on modern macos boxes.
**Summary**
**Changes**
> Specify platform linux/amd64 for images that are not multiarch

- localnode/docker-compose.yml
> docker: add missing profile

- localnode/docker-compose.yml
- localnode/docker-compose_mainnet.yml
> docker: update prysm and make option order consistant

- e2e/optimism-stack.Dockerfile
- localnode/docker-compose.yml
- localnode/docker-compose_mainnet.yml
**Summary**
update op-geth to the latest in localnode and localnet
**Changes**
see summary
> localnode: update op-geth to b0d955d

- e2e/optimism-stack.Dockerfile
- localnode/docker-compose.yml
- localnode/docker-compose_mainnet.yml
**Summary**
updated localnode+localnet to the latest op-geth
**Changes**
see summary
> update localnet+localnode to latest op-geth commit

- service/popm/popm_test.go
- service/tbc/rpc.go
**Summary**
fix function name in comment
**Changes**
> chore: fix function name in comment

- localnode/NODE_RUNNING.md
- localnode/gen-files.sh
- localnode/heminode.sh
> docker: Add profile awareness to heminode tmux script

- localnode/docker-compose_mainnet.yml
**Summary**
need to add the pectrablobschedule flag far in future to derive from l1 correctly
**Changes**
see summary
> re-add pectrablobschedule flag far in future

- bitcoin/wallet/gozer/tbcgozer/tbcgozer.go
- e2e/monitor/main.go
- e2e/monitor/main_test.go
- service/bfg/bfg.go
- service/hproxy/hproxy_test.go
- service/popm/popm.go
- service/popm/popm_test.go
- service/tbc/peer/peer_test.go
- service/tbc/peermanager.go
- service/tbc/rpc_test.go
- service/tbc/tbc.go
- service/tbc/tbc_test.go
- service/tbc/tbcfork_test.go
- testutil/mock/geth.go
- ttl/ttl.go
**Summary**
Same as #572 
**Changes**
Fixes #566
> all: replace time.After with time.Tick

- service/bfg/bfg_test.go
**Summary**
fix fragile test by adding a retry to sending finality http requests in
tests.  I believe the root cause of this is within the handling of
responses between gozer <-> tbc, but the correct solution to that will
be needed to be debated internally.
for now, to get us past the "fragile test" hump, just retry the request
that contains that issue if it fails
fixes https://github.com/hemilabs/heminetwork/issues/605
**Changes**
see summary
> fix fragile test: TestKeystoneFinalityInheritance

- e2e/e2e_ext_test.go
**Summary**
e2e got broken during rebase.
> e2e: fix main rebase issue

- README.md
**Summary**
Rewrite the `README.md` file with up-to-date information.
**Changes**
> readme: rewrite and bring up-to-date

- database/tbcd/level/headercache.go
- e2e/monitor/main_test.go
- testutil/extract.go
**Summary**
fix some problematic function names
**Changes**
> all: fix miscellaneous godoc function names

- CHANGELOG.md
> version: prepare to release v2.0.0

- service/tbc/indexer.go
- service/tbc/keystoneindex.go
**Summary**
This keeps breaking for some reason. I will lart the next person that touches this code.
> tbc: Fix genesis for keystones, AGAIN

- service/tbc/keystoneindex_test.go
**Summary**
see title
**Changes**
see summary
> tbcd: add test coverage for the genesis value on a keystone indexer
